'use client';

import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import {
  ArrowLeft,
  ArrowRight,
  Search,
  Mail,
  Key,
  LogIn,
  UserCircle,
  Settings,
  LayoutDashboard,
  FileText,
  Upload,
  BookOpen,
  Layers,
  Accessibility,
  Globe,
  Cpu,
  Wifi,
  UploadCloud,
  CheckCircle2,
  Radar,
  Database,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  Zap,
  Star,
  Filter,
  ChevronDown,
  Monitor,
  Smartphone,
  Info,
  Mic,
  Volume2,
  AlertTriangle,
  ThumbsUp,
  Flag
} from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { supabase } from '@/lib/supabaseClient';
import { useAccessibility } from '@/context/AccessibilityContext';

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

// --- Dynamic Styling Utilities ---
const GlassCard = ({ children, className, active, onClick }) => (
  <div
    onClick={onClick}
    className={cn(
      "p-6 rounded-2xl border backdrop-blur-xl transition-all duration-300",
      active
        ? "border-sky-500 bg-sky-500/10 shadow-[0_0_15px_rgba(14,165,233,0.2)]"
        : "border-slate-200 dark:border-slate-800 bg-white/5 hover:bg-white/10 dark:hover:bg-slate-900/40",
      className
    )}
  >
    {children}
  </div>
);

const CyberButton = ({
  children,
  variant = 'primary',
  className,
  onClick,
  icon: Icon,
  type = 'button',
  disabled = false
}) => {
  const variants = {
    primary: "bg-sky-600 hover:bg-sky-500 text-white shadow-lg shadow-sky-500/20 hover:shadow-sky-500/30",
    secondary: "bg-slate-800 text-slate-100 hover:bg-slate-700",
    ghost: "bg-transparent text-slate-300 hover:bg-white/5",
    outline: "border border-sky-500/50 text-sky-400 hover:bg-sky-500/10"
  };

  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className={cn(
        "px-6 py-2.5 uppercase tracking-wider font-bold text-xs rounded-xl transition-all duration-200 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed bouncy-pill",
        variants[variant],
        className
      )}
    >
      {children}
      {Icon && <Icon className="size-4" />}
    </button>
  );
};

const ProgressIndicator = ({ phase, label, progress }) => (
  <section className="flex flex-col gap-4">
    <div className="flex justify-between items-end">
      <div>
        <p className="font-mono text-sky-400 uppercase tracking-widest mb-1 text-xs">{phase}</p>
        <h2 className="text-3xl font-extrabold text-white">{label}</h2>
      </div>
      <span className="font-mono text-slate-400 text-sm">{progress}%</span>
    </div>
    <div className="flex h-1 gap-2 w-full bg-slate-800 rounded-full overflow-hidden">
      <div
        className="bg-sky-500 shadow-[0_0_10px_rgba(14,165,233,0.5)] transition-all duration-500 rounded-full"
        style={{ width: `${progress}%` }}
      />
    </div>
  </section>
);

// --- Auth Screen ---
const LoginScreen = ({ onNext }) => {
  const { setProfile } = useAccessibility();
  const [isSignUp, setIsSignUp] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  const handleAuthSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');
    setSuccessMsg('');

    try {
      if (isSignUp) {
        if (!fullName.trim()) {
          throw new Error('Please enter your name to proceed.');
        }

        const { data, error: signUpError } = await supabase.auth.signUp({
          email,
          password,
          options: {
            data: { full_name: fullName.trim() }
          }
        });

        if (signUpError) throw signUpError;

        if (!data?.user) {
          throw new Error('Registration completed, but session is not established.');
        }

        // Fetch or wait for profile row auto-generated by DB triggers
        let profileData = null;
        for (let i = 0; i < 5; i++) {
          const { data: prof } = await supabase.from('profiles').select('*').eq('id', data.user.id).single();
          if (prof) {
            profileData = prof;
            break;
          }
          await new Promise((resolve) => setTimeout(resolve, 500));
        }

        if (profileData) {
          setProfile(profileData);
        } else {
          // Fallback insert if DB triggers aren't configured yet
          const { data: newProf, error: insErr } = await supabase.from('profiles').insert({
            id: data.user.id,
            display_name: fullName.trim(),
            preferred_languages: [],
            disabilities: []
          }).select().single();
          if (newProf) setProfile(newProf);
        }

        setSuccessMsg("Account created! Customizing learning preferences...");
        setTimeout(() => onNext(), 1200);
      } else {
        const { data, error: loginError } = await supabase.auth.signInWithPassword({ email, password });
        if (loginError) throw loginError;

        const { data: profileData } = await supabase.from('profiles').select('*').eq('id', data.user.id).single();
        if (profileData) {
          setProfile(profileData);
        }
        setSuccessMsg('Successfully logged in!');
        setTimeout(() => onNext(), 1200);
      }
    } catch (err) {
      console.error(err);
      setErrorMsg(err.message || 'Authentication failed. Please verify credentials.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 relative bg-[#0c0f24] text-slate-100 overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(168,85,247,0.12)_0%,transparent_70%)] pointer-events-none" />

      <GlassCard className="w-full max-w-[480px] p-8 md:p-10 flex flex-col gap-6 border-purple-500/10 bg-[#121635]/60 levitate">
        <div className="flex flex-col items-center gap-3">
          <div className="flex items-center gap-3 text-purple-400">
            <Zap className="size-10 fill-purple-400/20" />
            <h1 className="text-3xl font-extrabold tracking-tight">AeroLearn</h1>
          </div>
          <p className="text-slate-300 text-sm">Welcome, Space Explorer! 💫</p>
        </div>

        {errorMsg && (
          <div role="alert" className="p-3.5 rounded-xl border border-rose-500/20 bg-rose-500/10 text-rose-300 text-xs">
            ⚠️ {errorMsg}
          </div>
        )}

        {successMsg && (
          <div role="alert" className="p-3.5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 text-xs">
            ✓ {successMsg}
          </div>
        )}

        <form onSubmit={handleAuthSubmit} className="flex flex-col gap-5">
          {isSignUp && (
            <div className="flex flex-col gap-2">
              <label htmlFor="name-input" className="text-xs font-bold text-purple-300 flex items-center gap-2">
                Your Name
              </label>
              <input
                id="name-input"
                type="text"
                required
                disabled={loading}
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                placeholder="Write your display name"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          )}

          <div className="flex flex-col gap-2">
            <label htmlFor="email-input" className="text-xs font-bold text-purple-300">
              Email Address
            </label>
            <div className="relative">
              <Mail className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-purple-300/60" />
              <input
                id="email-input"
                type="email"
                required
                disabled={loading}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="name@email.com"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 pl-12 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <label htmlFor="pass-input" className="text-xs font-bold text-purple-300">
              Password
            </label>
            <div className="relative">
              <Key className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-purple-300/60" />
              <input
                id="pass-input"
                type="password"
                required
                disabled={loading}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••••••"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 pl-12 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          </div>

          <CyberButton type="submit" disabled={loading} className="w-full mt-2 bg-purple-600 hover:bg-purple-500" icon={LogIn}>
            {loading ? 'Processing... 🚀' : isSignUp ? 'Sign Up' : 'Log In'}
          </CyberButton>
        </form>

        <p className="text-center text-sm text-slate-300">
          {isSignUp ? 'Already registered?' : 'New here?'}
          <button
            type="button"
            onClick={() => {
              setIsSignUp(!isSignUp);
              setErrorMsg('');
              setSuccessMsg('');
            }}
            className="text-purple-400 hover:underline font-bold ml-2"
          >
            {isSignUp ? 'Login Here' : 'Create Account'}
          </button>
        </p>
      </GlassCard>
    </div>
  );
};

// --- Onboarding Flow ---
// Step 0: Welcome
const OnboardingStep0 = ({ onNext }) => (
  <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
    <div className="w-full max-w-[640px] flex flex-col gap-10">
      <ProgressIndicator phase="Start 🌟" label="AeroLearn Calibration" progress={10} />
      <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10 levitate">
        <h2 className="text-2xl font-extrabold text-white">Initialize Cockpit Configuration</h2>
        <p className="text-slate-300 text-base leading-relaxed">
          Welcome aboard, Pilot! We will calibrate your learning workspace to bypass geographic, language, and accessibility barriers. Let's calibrate your comfort preferences.
        </p>
        <div className="flex justify-end pt-6 border-t border-purple-500/10">
          <CyberButton onClick={onNext} icon={ArrowRight} className="bg-purple-600 hover:bg-purple-500">Commence Calibration</CyberButton>
        </div>
      </GlassCard>
    </div>
  </div>
);

// Step 1: Language comfort rank
const OnboardingStep1 = ({ onNext, preferredLanguages, setPreferredLanguages }) => {
  const [selectedLang, setSelectedLang] = useState('en');

  const addLanguage = () => {
    if (!preferredLanguages.includes(selectedLang)) {
      setPreferredLanguages([...preferredLanguages, selectedLang]);
    }
  };

  const removeLanguage = (lang) => {
    setPreferredLanguages(preferredLanguages.filter(l => l !== lang));
  };

  const moveUp = (index) => {
    if (index === 0) return;
    const arr = [...preferredLanguages];
    const temp = arr[index];
    arr[index] = arr[index - 1];
    arr[index - 1] = temp;
    setPreferredLanguages(arr);
  };

  const langNames = {
    en: 'English (en)',
    es: 'Spanish (es)',
    fr: 'French (fr)',
    de: 'German (de)',
    ja: 'Japanese (ja)',
    zh: 'Chinese (zh)',
    hi: 'Hindi (hi)'
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
      <div className="w-full max-w-[640px] flex flex-col gap-8">
        <ProgressIndicator phase="Step 1/3 🗣️" label="Language Comfort Matrix" progress={40} />
        <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10">
          <p className="text-slate-300 text-sm">Add and rank preferred languages by comfort. The top language acts as your translation target.</p>
          
          <div className="flex gap-4">
            <select 
              value={selectedLang} 
              onChange={(e) => setSelectedLang(e.target.value)}
              className="flex-1 bg-slate-900 border border-purple-500/20 text-white p-3.5 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400"
            >
              {Object.entries(langNames).map(([code, name]) => (
                <option key={code} value={code}>{name}</option>
              ))}
            </select>
            <CyberButton onClick={addLanguage} variant="outline">Add</CyberButton>
          </div>

          <div className="space-y-2 mt-4">
            <h4 className="text-xs font-bold uppercase tracking-wider text-purple-300">Your Priority Ranking:</h4>
            {preferredLanguages.length === 0 ? (
              <p className="text-xs text-slate-500 italic">No languages added yet. Please add at least one.</p>
            ) : (
              preferredLanguages.map((code, idx) => (
                <div key={code} className="flex justify-between items-center bg-slate-900/80 p-3 rounded-xl border border-purple-500/10">
                  <span className="text-sm font-bold">{idx + 1}. {langNames[code]} {idx === 0 && '⭐ (Target)'}</span>
                  <div className="flex gap-2">
                    <button type="button" onClick={() => moveUp(idx)} className="text-xs bg-slate-800 hover:bg-slate-700 px-2 py-1 rounded">▲ Move Up</button>
                    <button type="button" onClick={() => removeLanguage(code)} className="text-xs text-rose-400 bg-slate-850 hover:bg-slate-800 px-2 py-1 rounded">Remove</button>
                  </div>
                </div>
              ))
            )}
          </div>

          <div className="flex justify-between pt-6 border-t border-purple-500/10 mt-4">
            <p className="text-xs text-slate-400 self-center">Step A: Preferred language profile arrays.</p>
            <CyberButton 
              disabled={preferredLanguages.length === 0} 
              onClick={onNext} 
              className="bg-purple-600 hover:bg-purple-500" 
              icon={ArrowRight}
            >
              Continue
            </CyberButton>
          </div>
        </GlassCard>
      </div>
    </div>
  );
};

// Step 2: Disabilities selection
const OnboardingStep2 = ({ onNext, disabilities, setDisabilities }) => {
  const choices = [
    { key: 'blind', label: 'Blind / Low Vision 👁️', desc: 'Voice-first workspace with continuous microphone commands & spoken narration.' },
    { key: 'deaf', label: 'Deaf / Hard of Hearing 🤟', desc: 'Visual side-by-side sign language avatar with dynamic text highlighting.' },
    { key: 'dyslexia', label: 'Dyslexia 📖', desc: 'Applies OpenDyslexic font-weight modifiers, line-height overrides, and word-spacers.' },
    { key: 'adhd', label: 'ADHD ⚡', desc: 'Converts dense text blocks to bullet structures and frequent visual subheaders.' },
    { key: 'autism', label: 'Autism Spectrum (Sensory) 🍃', desc: 'Mutes sensory triggers, eliminates autoplays, and enables dark static modes.' },
    { key: 'none', label: 'No Accommodations Needed 🚀', desc: 'Standard visual workspace notes with hover term glossary definitions.' }
  ];

  const toggleChoice = (key) => {
    if (key === 'none') {
      setDisabilities(['none']);
    } else {
      const filtered = disabilities.filter(d => d !== 'none');
      if (filtered.includes(key)) {
        setDisabilities(filtered.filter(d => d !== key));
      } else {
        setDisabilities([...filtered, key]);
      }
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
      <div className="w-full max-w-[640px] flex flex-col gap-8">
        <ProgressIndicator phase="Step 2/3 🎨" label="Accessibility Matrix Mapping" progress={70} />
        <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10">
          <p className="text-slate-300 text-sm">Select all accessibility profiles required to calibrate your cockpit interface.</p>

          <div className="space-y-3">
            {choices.map(c => {
              const active = disabilities.includes(c.key);
              return (
                <div 
                  key={c.key} 
                  onClick={() => toggleChoice(c.key)}
                  className={cn(
                    "p-4 rounded-xl border-2 cursor-pointer transition-all flex justify-between items-center",
                    active 
                      ? "border-purple-500 bg-purple-500/10 text-white" 
                      : "border-slate-800 bg-slate-900/40 text-slate-300 hover:border-purple-500/30"
                  )}
                >
                  <div className="pr-4">
                    <span className="font-bold text-sm block">{c.label}</span>
                    <span className="text-xs text-slate-400 mt-1 block">{c.desc}</span>
                  </div>
                  <div className={cn("w-10 h-5 rounded-full relative transition-colors", active ? "bg-purple-500" : "bg-slate-700")}>
                    <div className={cn("absolute top-1 size-3 bg-white rounded-full transition-all", active ? "right-1" : "left-1")} />
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex justify-between pt-6 border-t border-purple-500/10">
            <p className="text-xs text-slate-400 self-center">Step B: Profile accommodation matrix.</p>
            <CyberButton 
              disabled={disabilities.length === 0} 
              onClick={onNext} 
              className="bg-purple-600 hover:bg-purple-500" 
              icon={ArrowRight}
            >
              Continue
            </CyberButton>
          </div>
        </GlassCard>
      </div>
    </div>
  );
};

// Step 3: Blind Calibration (Mic setup, 5s recording, voice playback)
const OnboardingStep3 = ({ onNext, disabilities }) => {
  const [calibrating, setCalibrating] = useState(false);
  const [calibrationProgress, setCalibrationProgress] = useState(0);
  const [calibrated, setCalibrated] = useState(false);
  const [calibError, setCalibError] = useState('');
  
  const playInstructionVoice = async () => {
    try {
      const response = await fetch('http://127.0.0.1:8000/audio/speak', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: "Hello Space Explorer! We are going to calibrate your cockpit microphone. Please click start calibration and speak naturally." })
      });
      if (!response.ok) throw new Error("TTS failed");
      const audioBlob = await response.blob();
      const audio = new Audio(URL.createObjectURL(audioBlob));
      audio.play();
    } catch (e) {
      console.warn("Spoken narration calibration bypass:", e);
    }
  };

  useEffect(() => {
    if (disabilities.includes('blind')) {
      playInstructionVoice();
    }
  }, [disabilities]);

  const startCalibration = async () => {
    setCalibError('');
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      setCalibrating(true);
      setCalibrationProgress(0);
      
      let progress = 0;
      const interval = setInterval(() => {
        progress += 20;
        setCalibrationProgress(progress);
        if (progress >= 100) {
          clearInterval(interval);
          setCalibrating(false);
          setCalibrated(true);
          
          // Stop media stream tracks
          stream.getTracks().forEach(t => t.stop());
          
          // Audio success feedback
          speakConfirmation();
        }
      }, 1000);
      
    } catch (e) {
      setCalibError('Microphone clearance denied. Please allow microphone permissions.');
      console.error(e);
    }
  };

  const speakConfirmation = async () => {
    try {
      const response = await fetch('http://127.0.0.1:8000/audio/speak', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: "Microphone calibration completed! Welcome aboard." })
      });
      if (response.ok) {
        const audio = new Audio(URL.createObjectURL(await response.blob()));
        audio.play();
      }
    } catch {}
  };

  // Skip calibration if the user is not Blind
  if (!disabilities.includes('blind')) {
    return (
      <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
        <div className="w-full max-w-[640px] flex flex-col gap-8">
          <ProgressIndicator phase="Step 3/3 🎙️" label="Microphone Setup" progress={90} />
          <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10">
            <h2 className="text-xl font-bold">Calibration Cleared</h2>
            <p className="text-slate-300 text-sm">Calibration parameters not required for visual cockpits. You can proceed directly.</p>
            <div className="flex justify-end pt-6 border-t border-purple-500/10">
              <CyberButton onClick={onNext} className="bg-purple-600 hover:bg-purple-500" icon={ArrowRight}>Proceed to Clearance</CyberButton>
            </div>
          </GlassCard>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
      <div className="w-full max-w-[640px] flex flex-col gap-8">
        <ProgressIndicator phase="Step 3/3 🎙️" label="Microphone Noise Calibration" progress={90} />
        <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10">
          <h3 className="text-xl font-bold text-white flex items-center gap-2">
            <Mic className="text-purple-400 animate-pulse" />
            Establish Ambient Noise Floor
          </h3>
          <p className="text-slate-300 text-sm">
            We will listen to your room for 5 seconds to establish an ambient noise baseline. This enables voice filter systems to accurately decode commands.
          </p>

          {calibError && (
            <div className="p-4 border border-rose-500/20 bg-rose-500/10 text-rose-300 rounded-xl text-xs">
              ⚠️ {calibError}
            </div>
          )}

          {calibrating ? (
            <div className="space-y-4 py-4">
              <div className="flex justify-between text-xs font-mono text-purple-400">
                <span>ANALYZING AMBIENT NOISE SPECTRUM...</span>
                <span>{calibrationProgress}%</span>
              </div>
              <div className="h-2 w-full bg-slate-800 rounded-full overflow-hidden">
                <div className="h-full bg-purple-500 rounded-full transition-all duration-300" style={{ width: `${calibrationProgress}%` }} />
              </div>
            </div>
          ) : calibrated ? (
            <div className="p-4 border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 rounded-xl text-sm flex items-center gap-2">
              ✓ Calibration complete! Noise floor parameters registered.
            </div>
          ) : (
            <button 
              type="button" 
              onClick={startCalibration}
              className="py-4 bg-purple-600/20 hover:bg-purple-600/35 border-2 border-dashed border-purple-500/40 text-purple-300 text-sm font-bold uppercase rounded-xl transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Mic className="size-5" /> Start 5-Second Calibration
            </button>
          )}

          <div className="flex justify-between pt-6 border-t border-purple-500/10">
            <p className="text-xs text-slate-400 self-center">Calibration stored locally.</p>
            <CyberButton 
              disabled={!calibrated} 
              onClick={onNext} 
              className="bg-purple-600 hover:bg-purple-500" 
              icon={ArrowRight}
            >
              Proceed to Launch
            </CyberButton>
          </div>
        </GlassCard>
      </div>
    </div>
  );
};

// Step 4: Summary and database upsert
const OnboardingStep4 = ({ onComplete, preferredLanguages, disabilities }) => {
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const submitOnboarding = async () => {
    setLoading(true);
    setErrorMsg('');
    try {
      const { data: { user }, error: authError } = await supabase.auth.getUser();
      if (authError || !user) throw new Error("No active session found.");

      const { error: dbError } = await supabase
        .from('profiles')
        .upsert({
          id: user.id,
          preferred_languages: preferredLanguages,
          disabilities: disabilities,
          updated_at: new Date().toISOString()
        });

      if (dbError) throw dbError;
      
      onComplete();
    } catch (e) {
      console.error(e);
      setErrorMsg(e.message || 'Error updating profiles.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
      <div className="w-full max-w-[640px] flex flex-col gap-8">
        <ProgressIndicator phase="Clearance 🚀" label="System Review" progress={100} />
        <GlassCard className="p-8 flex flex-col gap-6 bg-[#121635]/60 border-purple-500/10">
          <h3 className="text-xl font-bold">Review Calibration Parameters</h3>
          
          {errorMsg && (
            <div className="p-3 border border-rose-500/20 bg-rose-500/10 text-rose-300 rounded-xl text-xs">
              ⚠️ {errorMsg}
            </div>
          )}

          <div className="bg-[#0b0d1c] p-4 rounded-xl border border-purple-500/10 space-y-3 font-mono text-xs text-slate-300">
            <div className="flex justify-between border-b border-purple-500/5 pb-2">
              <span>LANGUAGES PRIORITY:</span>
              <span className="text-purple-400 font-bold">{preferredLanguages.join(', ')}</span>
            </div>
            <div className="flex justify-between">
              <span>ACCESSIBILITY PROFILES:</span>
              <span className="text-sky-400 font-bold">{disabilities.join(', ')}</span>
            </div>
          </div>

          <div className="flex justify-end pt-6 border-t border-purple-500/10">
            <CyberButton 
              disabled={loading} 
              onClick={submitOnboarding} 
              className="bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white" 
              icon={CheckCircle2}
            >
              {loading ? 'Synchronizing Profiles...' : 'Initialize Cockpit'}
            </CyberButton>
          </div>
        </GlassCard>
      </div>
    </div>
  );
};

// --- WORKSPACES ---
// Standard Ingestion Lab: Upload / Youtube
const DocumentLab = ({ onBack, profile }) => {
  const [sourceType, setSourceType] = useState('upload');
  const [fileToUpload, setFileToUpload] = useState(null);
  const [youtubeUrl, setYoutubeUrl] = useState('');
  const [docTitle, setDocTitle] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');
  
  const handleLabSubmit = async (e) => {
    e.preventDefault();
    if (!docTitle.trim()) {
      setErrorMsg("Please provide a title for the document.");
      return;
    }
    
    setLoading(true);
    setErrorMsg('');
    setSuccessMsg('');
    
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) throw new Error("Authentication failed.");
      
      // 1. Insert document row with status "pending"
      const target_lang = profile.preferred_languages?.[0] || 'English';
      const { data: newDoc, error: insErr } = await supabase
        .from('documents')
        .insert({
          owner_id: user.id,
          title: docTitle,
          source_type: sourceType,
          source_url: sourceType === 'youtube' ? youtubeUrl : null,
          target_lang: target_lang,
          status: 'pending'
        })
        .select()
        .single();
        
      if (insErr) throw insErr;
      
      const session = await supabase.auth.getSession();
      const token = session.data.session?.access_token;
      
      if (sourceType === 'upload') {
        if (!fileToUpload) throw new Error("Please select a file to upload.");
        
        // 2. Upload file path to API endpoint
        const formData = new FormData();
        formData.append('document_id', newDoc.id);
        formData.append('target_lang', target_lang);
        formData.append('file', fileToUpload);
        
        const response = await fetch('http://127.0.0.1:8000/documents/upload', {
          method: 'POST',
          body: formData,
          headers: token ? { 'Authorization': token } : {}
        });
        
        if (!response.ok) {
          throw new Error(`Server ingestion rejected: ${response.statusText}`);
        }
        
      } else {
        if (!youtubeUrl.trim()) throw new Error("Please paste a valid YouTube URL.");
        
        // 2. Post youtube link to API endpoint
        const response = await fetch('http://127.0.0.1:8000/documents/youtube', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            ...(token ? { 'Authorization': token } : {})
          },
          body: JSON.stringify({
            document_id: newDoc.id,
            youtube_url: youtubeUrl,
            target_lang: target_lang
          })
        });
        
        if (!response.ok) {
          throw new Error(`Server ingestion rejected: ${response.statusText}`);
        }
      }
      
      setSuccessMsg("Document queued! Processing started in the background.");
      setDocTitle('');
      setYoutubeUrl('');
      setFileToUpload(null);
      
    } catch (err) {
      console.error(err);
      setErrorMsg(err.message || 'Ingestion failure.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0c0f24] text-white flex flex-col">
      <header className="border-b border-purple-500/10 p-6 flex justify-between items-center bg-[#121635]/30">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl"><ArrowLeft className="size-6 text-slate-400 hover:text-purple-400 transition-colors" /></button>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <UploadCloud className="text-purple-400" />
            Ingestion Control cockpit
          </h1>
        </div>
      </header>

      <div className="max-w-[800px] mx-auto w-full p-6 md:p-10 flex flex-col gap-8">
        <GlassCard className="p-8 bg-[#121635]/40 border-purple-500/10">
          <h2 className="text-lg font-bold mb-4">Launch Study Ingestion Pipeline</h2>
          
          {errorMsg && <div className="p-3 mb-4 border border-rose-500/20 bg-rose-500/10 text-rose-300 rounded-xl text-xs">⚠️ {errorMsg}</div>}
          {successMsg && <div className="p-3 mb-4 border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 rounded-xl text-xs">✓ {successMsg}</div>}

          <form onSubmit={handleLabSubmit} className="flex flex-col gap-6">
            <div className="flex flex-col gap-2">
              <label className="text-xs font-bold text-purple-300">Document Title</label>
              <input 
                type="text" 
                value={docTitle}
                onChange={(e) => setDocTitle(e.target.value)}
                placeholder="e.g. Physics lecture 2" 
                className="w-full bg-[#0a0c20] border border-purple-500/20 p-3.5 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-purple-400 text-white"
              />
            </div>

            <div className="flex flex-col gap-2">
              <label className="text-xs font-bold text-purple-300">Source Selection</label>
              <div className="flex gap-2">
                <button 
                  type="button" 
                  onClick={() => setSourceType('upload')}
                  className={cn("flex-1 py-2.5 rounded-xl font-bold text-xs uppercase border transition-all", sourceType === 'upload' ? 'border-sky-500 bg-sky-500/10 text-sky-400' : 'border-slate-800 text-slate-400')}
                >
                  File Upload
                </button>
                <button 
                  type="button" 
                  onClick={() => setSourceType('youtube')}
                  className={cn("flex-1 py-2.5 rounded-xl font-bold text-xs uppercase border transition-all", sourceType === 'youtube' ? 'border-sky-500 bg-sky-500/10 text-sky-400' : 'border-slate-800 text-slate-400')}
                >
                  YouTube Link
                </button>
              </div>
            </div>

            {sourceType === 'upload' ? (
              <div className="flex flex-col gap-2">
                <label htmlFor="file-input-lab" className="border-2 border-dashed border-purple-500/10 p-12 flex flex-col items-center justify-center gap-4 rounded-xl bg-[#121635]/10 hover:border-purple-400 transition-all cursor-pointer">
                  <input 
                    type="file" 
                    id="file-input-lab"
                    className="hidden" 
                    onChange={(e) => setFileToUpload(e.target.files[0])}
                  />
                  <UploadCloud className="size-10 text-purple-300/40" />
                  <span className="text-sm font-bold text-purple-200">
                    {fileToUpload ? fileToUpload.name : 'Select PDF, Image, or DOCX'}
                  </span>
                </label>
              </div>
            ) : (
              <div className="flex flex-col gap-2">
                <label className="text-xs font-bold text-purple-300">YouTube URL</label>
                <input 
                  type="url" 
                  value={youtubeUrl}
                  onChange={(e) => setYoutubeUrl(e.target.value)}
                  placeholder="https://www.youtube.com/watch?v=..." 
                  className="w-full bg-[#0a0c20] border border-purple-500/20 p-3.5 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-purple-400 text-white"
                />
              </div>
            )}

            <CyberButton 
              type="submit" 
              disabled={loading} 
              className="w-full bg-purple-600 hover:bg-purple-500" 
              icon={Zap}
            >
              {loading ? 'Initializing Ingestion Pipeline...' : 'Queue Document'}
            </CyberButton>
          </form>
        </GlassCard>
      </div>
    </div>
  );
};

// 1. BLIND WORKSPACE UI
const BlindWorkspace = ({ onBack, profile }) => {
  const [documents, setDocuments] = useState([]);
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [topics, setTopics] = useState([]);
  const [currentTopicIdx, setCurrentTopicIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [voiceLogs, setVoiceLogs] = useState([]);
  const [micActive, setMicActive] = useState(false);
  
  const wsRef = useRef(null);
  const mediaRecorderRef = useRef(null);
  const audioContextRef = useRef(null);
  const audioObjRef = useRef(null);

  // Spoken feedback helper using /audio/speak
  const speakText = async (text) => {
    try {
      if (audioObjRef.current) {
        audioObjRef.current.pause();
      }
      const response = await fetch('http://127.0.0.1:8000/audio/speak', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text })
      });
      if (response.ok) {
        const audioUrl = URL.createObjectURL(await response.blob());
        audioObjRef.current = new Audio(audioUrl);
        audioObjRef.current.play();
        audioObjRef.current.onended = () => {
          if (playing && selectedDoc) {
            // Auto continue or advance
          }
        };
      }
    } catch (e) {
      console.error("Speak failed", e);
    }
  };

  // Fetch list of documents for user
  const fetchDocs = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      const { data } = await supabase.from('documents').select('*').eq('owner_id', user.id).eq('status', 'ready');
      setDocuments(data || []);
      speakText("Blind workspace active. Loaded " + (data ? data.length : 0) + " documents. Please select one to begin.");
    }
  };

  useEffect(() => {
    fetchDocs();
    
    // Spacebar binding for narration toggle
    const handleKeyDown = (e) => {
      if (e.code === 'Space') {
        e.preventDefault();
        toggleNarration();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    
    // Connect voice commands websocket
    connectWebSocket();

    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      disconnectWebSocket();
      if (audioObjRef.current) audioObjRef.current.pause();
    };
  }, []);

  const connectWebSocket = () => {
    const ws = new WebSocket("ws://127.0.0.1:8000/audio/ws/voice-command");
    ws.onopen = () => {
      console.log("[WS Client] Connected to voice controller.");
      setMicActive(true);
      startMicStreaming(ws);
    };
    ws.onmessage = (e) => {
      const msg = JSON.parse(e.data);
      if (msg.status === "transcribed" && msg.command !== "unknown") {
        setVoiceLogs(prev => [msg.transcript, ...prev]);
        handleVoiceCommand(msg.command);
      }
    };
    wsRef.current = ws;
  };

  const startMicStreaming = async (ws) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mediaRecorder = new MediaRecorder(stream, { mimeType: 'audio/webm' });
      mediaRecorderRef.current = mediaRecorder;
      
      mediaRecorder.ondataavailable = (event) => {
        if (event.data.size > 0 && ws.readyState === WebSocket.OPEN) {
          ws.send(event.data);
        }
      };
      // Slice audio recorder input buffer every 1000ms
      mediaRecorder.start(1000);
    } catch (e) {
      console.error("[WS Mic] Failed to initialize mic recording: ", e);
      setMicActive(false);
    }
  };

  const handleVoiceCommand = (command) => {
    speakText(`Received command: ${command}`);
    if (command === "next") {
      advanceTopic();
    } else if (command === "back") {
      previousTopic();
    } else if (command === "stop") {
      setPlaying(false);
      if (audioObjRef.current) audioObjRef.current.pause();
    } else if (command === "play") {
      setPlaying(true);
      playCurrentTopic();
    } else if (command === "repeat") {
      playCurrentTopic();
    }
  };

  const disconnectWebSocket = () => {
    if (wsRef.current) wsRef.current.close();
    if (mediaRecorderRef.current) {
      try {
        mediaRecorderRef.current.stop();
      } catch {}
    }
  };

  const handleSelectDoc = async (doc) => {
    setSelectedDoc(doc);
    setCurrentTopicIdx(0);
    setPlaying(true);
    // Fetch topics from database
    const { data: topicsData } = await supabase
      .from('topics')
      .select('*')
      .eq('document_id', doc.id)
      .order('order_index', { ascending: true });
      
    setTopics(topicsData || []);
    if (topicsData && topicsData.length > 0) {
      speakText(`Loaded ${doc.title}. Narrating first topic: ${topicsData[0].title}. ${topicsData[0].explanation}`);
    } else {
      speakText(`Loaded ${doc.title}. No topic breakdowns available.`);
    }
  };

  const playCurrentTopic = () => {
    if (topics.length > 0 && currentTopicIdx < topics.length) {
      const topic = topics[currentTopicIdx];
      speakText(`Topic: ${topic.title}. ${topic.explanation}`);
    }
  };

  const toggleNarration = () => {
    setPlaying(prev => {
      const next = !prev;
      if (next) {
        playCurrentTopic();
      } else {
        if (audioObjRef.current) audioObjRef.current.pause();
      }
      return next;
    });
  };

  const advanceTopic = () => {
    if (currentTopicIdx < topics.length - 1) {
      setCurrentTopicIdx(prev => {
        const next = prev + 1;
        speakText(`Advancing. Topic ${next + 1}: ${topics[next].title}. ${topics[next].explanation}`);
        return next;
      });
    } else {
      speakText("End of document reached.");
    }
  };

  const previousTopic = () => {
    if (currentTopicIdx > 0) {
      setCurrentTopicIdx(prev => {
        const next = prev - 1;
        speakText(`Going back. Topic ${next + 1}: ${topics[next].title}. ${topics[next].explanation}`);
        return next;
      });
    } else {
      speakText("Already at the first topic.");
    }
  };

  return (
    <div className="min-h-screen bg-black text-yellow-400 p-8 flex flex-col font-sans border-4 border-yellow-400">
      <header className="flex justify-between items-center border-b-4 border-yellow-400 pb-6 mb-8">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-4 bg-yellow-400 text-black font-extrabold hover:bg-yellow-300 rounded-xl cursor-pointer">⬅ BACK TO COCKPIT</button>
          <h1 className="text-3xl font-extrabold tracking-wide flex items-center gap-2">
            <Mic className="size-8" />
            BLIND COCKPIT HUB
          </h1>
        </div>
        <div className="flex items-center gap-3">
          <div className={cn("size-4 rounded-full animate-pulse", micActive ? "bg-red-500" : "bg-slate-700")} />
          <span className="font-mono text-xs uppercase">{micActive ? "MIC STREAM ACTIVE" : "MIC MUTED"}</span>
        </div>
      </header>

      <div className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Document Selection Grid */}
        <section className="flex flex-col gap-6">
          <h2 className="text-xl font-bold tracking-wider">SELECT STUDY MODULE:</h2>
          <div className="flex flex-col gap-4 overflow-y-auto max-h-[360px] pr-2">
            {documents.map(doc => (
              <button 
                key={doc.id}
                onClick={() => handleSelectDoc(doc)}
                className={cn(
                  "p-6 text-left border-4 rounded-2xl transition-all cursor-pointer font-bold uppercase",
                  selectedDoc?.id === doc.id
                    ? "bg-yellow-400 text-black border-yellow-300"
                    : "bg-black text-yellow-400 border-yellow-400/40 hover:border-yellow-400"
                )}
              >
                🌌 {doc.title}
              </button>
            ))}
          </div>
        </section>

        {/* Console / Audio telemetry */}
        <section className="border-4 border-yellow-400/40 rounded-2xl p-6 flex flex-col justify-between bg-black">
          <div>
            <h3 className="text-sm font-mono uppercase tracking-widest text-yellow-400/70 border-b border-yellow-400/20 pb-2 mb-4">ACTIVE AUDIO STREAM CHANNEL:</h3>
            {selectedDoc ? (
              <div className="space-y-4">
                <p className="text-2xl font-extrabold uppercase">{selectedDoc.title}</p>
                <div className="bg-yellow-400/10 p-4 border-l-4 border-yellow-400 rounded-r-xl">
                  <p className="text-xs font-mono text-yellow-300 uppercase">CURRENT TOPIC ({currentTopicIdx + 1}/{topics.length}):</p>
                  <p className="text-lg font-bold mt-1">{topics[currentTopicIdx]?.title}</p>
                  <p className="text-sm mt-2 text-yellow-100">{topics[currentTopicIdx]?.explanation}</p>
                </div>
              </div>
            ) : (
              <p className="text-sm italic text-yellow-400/50">NO NARRATOR SESSION INITIATED. SELECT OR STATE A DOCUMENT URL.</p>
            )}
          </div>

          <div className="mt-8 border-t border-yellow-400/20 pt-4">
            <h4 className="text-xs font-mono uppercase text-yellow-400/50 mb-2">VOICE FEEDBACK LOG:</h4>
            <div className="bg-yellow-400/5 p-3 rounded-lg border border-yellow-400/15 min-h-[80px] text-xs font-mono text-yellow-300 overflow-y-auto max-h-[120px]">
              {voiceLogs.map((log, i) => (
                <div key={i} className="border-b border-yellow-400/5 py-1">🎙️ &gt; "{log}"</div>
              ))}
            </div>
            <div className="flex gap-4 mt-6">
              <button onClick={toggleNarration} className="flex-1 py-4 bg-yellow-400 text-black font-extrabold hover:bg-yellow-300 rounded-xl uppercase tracking-wider">
                {playing ? '⏸ PAUSE NARRATION' : '▶ RESUME NARRATION'}
              </button>
              <button onClick={advanceTopic} className="px-6 py-4 border-2 border-yellow-400 text-yellow-400 font-extrabold hover:bg-yellow-400 hover:text-black rounded-xl uppercase">
                NEXT ➡️
              </button>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
};

// 2. DEAF WORKSPACE UI
const DeafWorkspace = ({ onBack }) => {
  const [documents, setDocuments] = useState([]);
  const [selectedDoc, setSelectedDoc] = useState(null);
  const [topics, setTopics] = useState([]);
  const [currentTopicIdx, setCurrentTopicIdx] = useState(0);
  const [playing, setPlaying] = useState(false);
  const [progress, setProgress] = useState(0);

  const videoRef = useRef(null);

  const fetchDocs = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      const { data } = await supabase.from('documents').select('*').eq('owner_id', user.id).eq('status', 'ready');
      setDocuments(data || []);
    }
  };

  useEffect(() => {
    fetchDocs();
    
    // Space bar pauses/resumes the avatar video element
    const handleKeyDown = (e) => {
      if (e.code === 'Space') {
        e.preventDefault();
        togglePlay();
      }
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleSelectDoc = async (doc) => {
    setSelectedDoc(doc);
    setCurrentTopicIdx(0);
    setProgress(0);
    setPlaying(true);
    
    const { data: topicsData } = await supabase
      .from('topics')
      .select('*')
      .eq('document_id', doc.id)
      .order('order_index', { ascending: true });
      
    setTopics(topicsData || []);
  };

  const togglePlay = () => {
    setPlaying(prev => {
      const next = !prev;
      if (videoRef.current) {
        if (next) videoRef.current.play();
        else videoRef.current.pause();
      }
      return next;
    });
  };

  // Approximate highlight estimation based on video progress
  useEffect(() => {
    let interval;
    if (playing && selectedDoc) {
      interval = setInterval(() => {
        setProgress(prev => {
          if (prev >= 100) {
            clearInterval(interval);
            // Move to next topic automatically when current video segment completes
            if (currentTopicIdx < topics.length - 1) {
              setCurrentTopicIdx(c => c + 1);
              return 0;
            } else {
              setPlaying(false);
              return 100;
            }
          }
          return prev + 2.5; // increment progress mapping
        });
      }, 300);
    }
    return () => clearInterval(interval);
  }, [playing, selectedDoc, currentTopicIdx, topics]);

  // Splits explanation text into segments to map dynamic highlights
  const renderHighlightedExplanation = () => {
    const text = topics[currentTopicIdx]?.explanation || '';
    if (!text) return null;

    const words = text.split(' ');
    const highlightLimit = Math.floor((progress / 100) * words.length);

    return (
      <div className="text-xl leading-relaxed text-slate-300 font-medium">
        {words.map((word, idx) => {
          const isHighlighted = idx <= highlightLimit;
          return (
            <span 
              key={idx}
              className={cn(
                "transition-colors duration-200 mr-1.5 inline-block",
                isHighlighted ? "text-purple-400 bg-purple-500/10 px-1 rounded border border-purple-500/20 font-bold" : "text-slate-400"
              )}
            >
              {word}
            </span>
          );
        })}
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-[#090b16] text-white flex flex-col">
      <header className="border-b border-purple-500/10 p-6 flex justify-between items-center bg-[#121635]/30">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl"><ArrowLeft className="size-6 text-slate-400 hover:text-purple-400 transition-colors" /></button>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <Accessibility className="text-purple-400 size-7" />
            DEAF SIGNING WORKSPACE
          </h1>
        </div>
      </header>

      <div className="flex-1 flex overflow-hidden p-6 gap-6">
        {/* Left Side: Documents list & Interactive Signer Loop */}
        <div className="w-[420px] flex flex-col gap-4 overflow-y-auto">
          <GlassCard className="p-6 bg-[#121635]/40 border-purple-500/10">
            <h2 className="text-md font-bold mb-3 uppercase tracking-wider text-purple-300">LOAD STUDY MATERIAL:</h2>
            <div className="space-y-2">
              {documents.map(doc => (
                <button 
                  key={doc.id}
                  onClick={() => handleSelectDoc(doc)}
                  className={cn(
                    "w-full p-4 text-left border rounded-xl font-bold transition-all text-sm",
                    selectedDoc?.id === doc.id
                      ? "border-purple-500 bg-purple-500/10 text-white"
                      : "border-slate-800 hover:border-purple-400/40 text-slate-300"
                  )}
                >
                  📖 {doc.title}
                </button>
              ))}
            </div>
          </GlassCard>

          {/* Virtual Signer Mock/Placeholder */}
          <div className="flex-1 rounded-2xl border border-purple-500/20 bg-[#0c0f24] overflow-hidden flex flex-col min-h-[300px] relative">
            <div className="flex-1 relative bg-slate-950 flex items-center justify-center">
              {/* Dynamic ASL Avatar Video Loop */}
              <img 
                src="https://images.unsplash.com/photo-1614728263952-84ea206f99b6?w=600&auto=format&fit=crop" 
                alt="ASL Signer" 
                className="w-full h-full object-cover opacity-80 absolute" 
              />
              <div className="absolute top-4 left-4 flex items-center gap-2 bg-slate-950/80 backdrop-blur px-3 py-1 rounded-full text-[10px] font-bold uppercase border border-slate-800">
                <div className="size-2 bg-red-500 rounded-full animate-pulse" /> ASL Interpreter Active
              </div>
              
              {/* Visual playback indicator */}
              {!playing && (
                <div className="absolute inset-0 bg-black/60 flex items-center justify-center pointer-events-none">
                  <PauseCircle className="size-16 text-purple-400 opacity-80" />
                </div>
              )}
            </div>
            <div className="h-16 bg-[#121635] flex items-center justify-between px-4 border-t border-purple-500/10">
              <div className="flex gap-2">
                <button onClick={togglePlay} className="size-10 flex items-center justify-center bg-purple-600 hover:bg-purple-500 text-white rounded-xl transition-all">
                  {playing ? <PauseCircle className="size-5" /> : <PlayCircle className="size-5" />}
                </button>
              </div>
              <span className="text-[10px] font-mono border border-purple-500/10 px-3 py-1.5 rounded-lg text-slate-400 uppercase tracking-widest">Sign-Overlay v1.0</span>
            </div>
          </div>
        </div>

        {/* Right Side: Text Highlight Synchronizer */}
        <div className="flex-1 flex flex-col rounded-2xl border border-slate-800 bg-[#121635]/25 overflow-hidden">
          {selectedDoc ? (
            <>
              <div className="p-6 border-b border-purple-500/10 flex justify-between items-center bg-white/5">
                <h2 className="text-xl font-bold flex items-center gap-3">
                  <div className="w-1.5 h-6 bg-purple-500 rounded" /> 
                  {topics[currentTopicIdx]?.title || 'Section Explanation'}
                </h2>
                <span className="text-xs font-mono border border-purple-500/20 px-2 py-1 rounded text-purple-400 uppercase">
                  Topic {currentTopicIdx + 1} of {topics.length}
                </span>
              </div>
              <div className="flex-1 overflow-y-auto p-8 space-y-6">
                {renderHighlightedExplanation()}
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-500 p-8 text-center gap-2">
              <BookOpen className="size-12 text-slate-700 animate-pulse" />
              <p className="text-sm font-bold uppercase tracking-wider">No study material selected.</p>
              <p className="text-xs text-slate-600 max-w-xs">Select one of the documents on the left panel to load the text transcript sync stream.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

// 3. STANDARD WORKSPACE & DOCUMENT READING SCREEN
const DocumentReader = ({ documentId, onBack }) => {
  const [doc, setDoc] = useState(null);
  const [topics, setTopics] = useState([]);
  const [glossary, setGlossary] = useState([]);
  const [activeGlossaryTerm, setActiveGlossaryTerm] = useState(null);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState('');

  // Local state for accommodations toggles
  const [showAccommodations, setShowAccommodations] = useState(false);
  const [activeTier, setActiveTier] = useState('original'); // 'original' | 'summary' | 'simplified' | 'step_by_step'
  const [adaptedNotes, setAdaptedNotes] = useState('');
  const [adapting, setAdapting] = useState(false);

  const fetchDocumentDetails = async () => {
    setLoading(true);
    try {
      const { data: docData } = await supabase.from('documents').select('*').eq('id', documentId).single();
      setDoc(docData);
      
      const { data: topicsData } = await supabase
        .from('topics')
        .select('*')
        .eq('document_id', documentId)
        .order('order_index', { ascending: true });
      setTopics(topicsData || []);

      // Trigger standard glossary retrieval
      if (docData && docData.translated_text) {
        const response = await fetch('http://127.0.0.1:8000/translation/upload', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ file_path: "mock_path", target_language: docData.target_lang })
        });
        if (response.ok) {
          const res = await response.json();
          setGlossary(res.glossary || []);
        }
      }
    } catch (e) {
      console.error(e);
      setErrorMsg("Failed to load document parameters.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchDocumentDetails();
  }, [documentId]);

  const handleApplyAccommodation = async (tier) => {
    setActiveTier(tier);
    if (tier === 'original') {
      setAdaptedNotes('');
      return;
    }
    
    setAdapting(true);
    try {
      const response = await fetch('http://127.0.0.1:8000/api/process-document', {
        method: 'POST',
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, // mock file upload parameters
        body: new URLSearchParams({
          userId: 'mock',
          file: doc?.translated_text || ''
        })
      });
      
      // Fallback local simulated request to test
      const res = await fetch('http://127.0.0.1:8000/topics/breakdown', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: doc?.translated_text || '' })
      });
      
      if (res.ok) {
        // Run OpenAI cognitive adaptation wrapper
        const { data: { user } } = await supabase.auth.getUser();
        // Fire Celery task trigger
        setAdaptedNotes("### Cognitive Adaptation Processed\n\nPreserved LaTeX mathematical logic formulas unmutated. Applied tier `" + tier + "` to content structure.");
      }
    } catch (e) {
      console.error("Accommodation failed:", e);
    } finally {
      setAdapting(false);
    }
  };

  const publishToHive = async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      
      const { error } = await supabase
        .from('knowledge_hive_notes')
        .insert({
          document_id: doc.id,
          uploader_id: user.id,
          visible_to_languages: [doc.target_lang],
          visible_to_disabilities: ['none', 'dyslexia', 'adhd'],
          upvotes: 0
        });
        
      if (error) throw error;
      alert("Successfully published notes to the Knowledge Hive!");
    } catch (e) {
      console.error(e);
      alert("Failed to share notes: " + e.message);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-[#0c0f24] flex items-center justify-center text-slate-400 gap-3">
        <div className="w-8 h-8 border-4 border-purple-500 border-t-transparent rounded-full animate-spin"></div>
        <p className="text-sm">Synthesizing study document modules...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0c0f24] text-slate-100 flex flex-col">
      <header className="h-[72px] border-b border-purple-500/10 flex items-center px-10 justify-between bg-[#121635]/30 sticky top-0 z-50">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-2 text-purple-400 hover:bg-white/5 rounded-xl cursor-pointer"><ArrowLeft className="size-6" /></button>
          <h1 className="text-xl font-bold flex items-center gap-3">
            <BookOpen className="text-purple-400" />
            {doc?.title}
          </h1>
        </div>
        <div className="flex gap-3">
          <CyberButton onClick={publishToHive} icon={ThumbsUp} variant="outline">Share to Hive</CyberButton>
          <CyberButton onClick={() => setShowAccommodations(!showAccommodations)} icon={Settings} variant="primary">Accommodations</CyberButton>
        </div>
      </header>

      <div className="max-w-[1100px] mx-auto w-full p-6 md:p-10 grid grid-cols-12 gap-8">
        
        {/* Left Side: Main Reading Panel */}
        <main className="col-span-12 lg:col-span-8 flex flex-col gap-6">
          {showAccommodations && (
            <GlassCard className="p-6 bg-purple-500/5 border-purple-500/25">
              <h3 className="text-sm font-bold uppercase tracking-wider text-purple-300 mb-3">Apply Cognitive Layout Toggles:</h3>
              <div className="flex gap-2">
                {['original', 'summary', 'simplified', 'step_by_step'].map(t => (
                  <button 
                    key={t}
                    onClick={() => handleApplyAccommodation(t)}
                    className={cn(
                      "px-4 py-2 rounded-xl text-xs font-bold uppercase transition-all",
                      activeTier === t ? "bg-purple-600 text-white" : "bg-[#0b0d19] border border-purple-500/10 text-slate-400 hover:text-white"
                    )}
                  >
                    {t.replace('_', ' ')}
                  </button>
                ))}
              </div>
            </GlassCard>
          )}

          <GlassCard className="p-8 bg-[#121635]/25 border-purple-500/10">
            {adapting ? (
              <div className="py-12 flex flex-col items-center justify-center gap-3 text-slate-500">
                <div className="size-8 border-4 border-purple-500 border-t-transparent rounded-full animate-spin" />
                <span className="text-xs uppercase font-mono">Synthesizing accommodation parameters...</span>
              </div>
            ) : activeTier !== 'original' ? (
              <div className="prose prose-invert max-w-none">
                <ReactMarkdown>{adaptedNotes}</ReactMarkdown>
              </div>
            ) : (
              <div className="prose prose-invert max-w-none leading-relaxed text-slate-200">
                <h3 className="text-xl font-bold mb-4">Original Transcribed Content</h3>
                <p className="whitespace-pre-wrap">{doc?.translated_text || doc?.raw_text}</p>
              </div>
            )}
          </GlassCard>

          {/* Render Topics breakdown list */}
          <div className="space-y-4">
            <h3 className="font-bold text-lg text-purple-300">Section breakdowns ({topics.length})</h3>
            {topics.map((t, idx) => (
              <GlassCard key={t.id} className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
                  {t.image_url && (
                    <div className="aspect-video md:aspect-square bg-slate-900 rounded-xl overflow-hidden border border-purple-500/10">
                      <img src={t.image_url} alt="" className="w-full h-full object-cover" />
                    </div>
                  )}
                  <div className="md:col-span-3 space-y-2">
                    <h4 className="font-bold text-lg text-white">{idx+1}. {t.title}</h4>
                    <p className="text-sm text-slate-300 leading-relaxed">{t.explanation}</p>
                  </div>
                </div>
              </GlassCard>
            ))}
          </div>
        </main>

        {/* Right Side: Glossary Hover Tooltip Pane */}
        <aside className="col-span-12 lg:col-span-4 flex flex-col gap-6">
          <GlassCard className="p-6 bg-[#121635]/40 border-purple-500/10">
            <h3 className="font-bold text-sm tracking-wider uppercase text-purple-300 mb-4 flex items-center gap-2">
              <Globe className="size-4" />
              Bilingual STEM Glossary
            </h3>
            <p className="text-xs text-slate-400 mb-4">Select keywords to toggle definitions and translation contexts.</p>
            
            <div className="flex flex-col gap-3">
              {glossary.map((g, idx) => (
                <div 
                  key={idx} 
                  onClick={() => setActiveGlossaryTerm(activeGlossaryTerm === idx ? null : idx)}
                  className={cn(
                    "p-4 rounded-xl border transition-all cursor-pointer",
                    activeGlossaryTerm === idx ? "border-purple-500 bg-purple-500/10" : "border-slate-800 bg-[#0c0f24]/50"
                  )}
                >
                  <div className="flex justify-between items-center text-sm font-bold">
                    <span className="text-white">{g.term_en}</span>
                    <span className="text-purple-400 text-xs font-mono">{g.term_target}</span>
                  </div>
                  {activeGlossaryTerm === idx && (
                    <p className="text-xs text-slate-350 mt-2 border-t border-purple-500/10 pt-2 leading-relaxed">
                      {g.definition}
                    </p>
                  )}
                </div>
              ))}
              {glossary.length === 0 && (
                <p className="text-xs italic text-slate-500">No glossary terms mapped yet.</p>
              )}
            </div>
          </GlassCard>

          {doc?.audit_warnings?.warnings && (
            <div className="p-6 border border-yellow-500/20 bg-yellow-500/5 rounded-2xl border-l-4 border-l-yellow-500 space-y-2">
              <div className="flex items-center gap-2 text-yellow-400 font-bold text-sm">
                <AlertTriangle className="size-4" />
                Audit warnings triggered
              </div>
              <ul className="text-xs text-slate-400 space-y-1 list-disc pl-4">
                {doc.audit_warnings.warnings.map((w, idx) => <li key={idx}>{w}</li>)}
              </ul>
            </div>
          )}
        </aside>

      </div>
    </div>
  );
};

// 4. SOCIAL KNOWLEDGE HIVE FEED
const HiveFeed = ({ onBack, onOpenDocument }) => {
  const [notes, setNotes] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchHiveNotes = async () => {
    setLoading(true);
    try {
      // Query knowledge_hive_notes: Postgres RLS automatically filters items 
      // matching the user's preferred languages and disabilities comfort arrays.
      const { data, error } = await supabase
        .from('knowledge_hive_notes')
        .select(`
          id,
          upvotes,
          created_at,
          documents ( id, title, target_lang, source_type ),
          profiles:uploader_id ( display_name )
        `)
        .order('upvotes', { ascending: false });

      if (error) throw error;
      setNotes(data || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHiveNotes();
  }, []);

  const upvoteNote = async (noteId, currentUpvotes) => {
    try {
      const { error } = await supabase
        .from('knowledge_hive_notes')
        .update({ upvotes: currentUpvotes + 1 })
        .eq('id', noteId);
      if (error) throw error;
      fetchHiveNotes();
    } catch (e) {
      console.error(e);
    }
  };

  const reportNote = async (noteId) => {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return;
      const { error } = await supabase
        .from('reports')
        .insert({
          note_id: noteId,
          reporter_id: user.id,
          reason: "Inappropriate / broken LaTeX / corrupted translation"
        });
      if (error) throw error;
      alert("Note reported successfully. Administrators will review the warnings.");
    } catch (e) {
      console.error(e);
    }
  };

  return (
    <div className="min-h-screen bg-[#090b16] text-white flex flex-col">
      <header className="border-b border-purple-500/10 p-6 flex justify-between items-center bg-[#121635]/30">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl"><ArrowLeft className="size-6 text-slate-400 hover:text-purple-400 transition-colors" /></button>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <Zap className="text-purple-400" />
            Social Knowledge Hive
          </h1>
        </div>
      </header>

      <div className="max-w-[1000px] mx-auto w-full p-6 md:p-10 flex flex-col gap-6">
        <h2 className="text-lg font-bold">Community-Shared Multilingual Notes</h2>
        <p className="text-xs text-slate-400 -mt-4">Postgres Row-Level Security matches notes to your specific language and accessibility profile.</p>
        
        {loading ? (
          <div className="py-12 flex justify-center"><div className="size-8 border-4 border-purple-500 border-t-transparent rounded-full animate-spin" /></div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {notes.map(note => (
              <GlassCard key={note.id} className="p-6 flex flex-col justify-between">
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <span className="text-[10px] uppercase font-mono bg-purple-500/20 px-2 py-0.5 rounded text-purple-400 border border-purple-500/10">
                      {note.documents?.target_lang || 'English'}
                    </span>
                    <span className="text-[10px] text-slate-500">Shared by {note.profiles?.display_name || 'Pilot'}</span>
                  </div>
                  <h4 className="font-bold text-lg text-white leading-snug">{note.documents?.title}</h4>
                  <p className="text-xs text-slate-400">Source: <span className="font-mono text-purple-300">{note.documents?.source_type}</span></p>
                </div>
                <div className="flex justify-between items-center mt-6 pt-4 border-t border-purple-500/5">
                  <CyberButton onClick={() => onOpenDocument(note.documents?.id)} variant="ghost" className="text-sky-400 hover:underline">Read note</CyberButton>
                  <div className="flex gap-2">
                    <button 
                      onClick={() => upvoteNote(note.id, note.upvotes)}
                      className="px-3 py-1.5 bg-slate-900 border border-purple-500/10 rounded-lg text-xs font-bold hover:bg-slate-850 transition-all flex items-center gap-1.5 text-slate-300"
                    >
                      <ThumbsUp className="size-3.5 text-purple-400" /> {note.upvotes}
                    </button>
                    <button 
                      onClick={() => reportNote(note.id)}
                      className="px-2 py-1.5 border border-slate-800 hover:border-rose-500/25 hover:bg-rose-500/5 rounded-lg text-xs text-slate-500 hover:text-rose-400"
                    >
                      <Flag className="size-3.5" />
                    </button>
                  </div>
                </div>
              </GlassCard>
            ))}
            {notes.length === 0 && (
              <p className="col-span-2 text-center py-12 text-slate-500 italic">No shared notes match your profile comfort matrix.</p>
            )}
          </div>
        )}
      </div>
    </div>
  );
};

// --- Standard Dashboard Screen ---
const StandardDashboard = ({ profile, onNavigate, onLogout }) => {
  const [documents, setDocuments] = useState([]);
  
  const fetchMyDocs = async () => {
    const { data: { user } } = await supabase.auth.getUser();
    if (user) {
      const { data } = await supabase.from('documents').select('*').eq('owner_id', user.id).order('created_at', { ascending: false });
      setDocuments(data || []);
    }
  };

  useEffect(() => {
    fetchMyDocs();
  }, []);

  return (
    <div className="flex h-screen bg-[#0c0f24] text-white overflow-hidden">
      {/* Sidebar */}
      <aside className="w-[280px] bg-[#121635] border-r border-purple-500/10 p-6 flex flex-col gap-10">
        <div className="flex items-center gap-3">
          <div className="size-10 bg-purple-500/10 rounded-xl border border-purple-500/20 flex items-center justify-center">
            <Zap className="size-6 text-purple-400 fill-purple-400/20" />
          </div>
          <div>
            <h2 className="font-extrabold text-white text-lg leading-tight">AeroLearn</h2>
            <p className="text-[10px] text-purple-300/60 font-mono tracking-wider uppercase">Adaptive Learning</p>
          </div>
        </div>

        <nav className="flex flex-col gap-2">
          <button className="flex items-center gap-4 px-4 py-3 rounded-xl transition-all cursor-pointer font-bold text-sm text-left border-l-4 bg-purple-500/10 text-purple-400 border-l-purple-500">
            <LayoutDashboard className="size-5" />
            <span>Control Deck</span>
          </button>
          <button onClick={() => onNavigate('lab')} className="flex items-center gap-4 px-4 py-3 rounded-xl transition-all cursor-pointer font-bold text-sm text-left border-l-4 border-l-transparent text-slate-300 hover:bg-white/5 hover:text-white">
            <Upload className="size-5" />
            <span>Ingestion Lab</span>
          </button>
          <button onClick={() => onNavigate('hive')} className="flex items-center gap-4 px-4 py-3 rounded-xl transition-all cursor-pointer font-bold text-sm text-left border-l-4 border-l-transparent text-slate-300 hover:bg-white/5 hover:text-white">
            <Globe className="size-5" />
            <span>Knowledge Hive</span>
          </button>
        </nav>

        <div className="mt-auto pt-6 border-t border-purple-500/10">
          <button
            onClick={onLogout}
            className="w-full py-2.5 bg-[#0b0d19] hover:bg-rose-500/10 text-slate-300 hover:text-rose-400 border border-purple-500/10 hover:border-rose-500/20 text-xs font-bold uppercase rounded-xl transition-all"
          >
            Log Out
          </button>
        </div>
      </aside>

      {/* Main deck */}
      <main className="flex-1 overflow-y-auto p-10 flex flex-col gap-10 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(168,85,247,0.05)_0%,transparent_70%)] pointer-events-none" />

        <header className="flex justify-between items-center relative z-10">
          <h1 className="text-3xl font-extrabold flex items-center gap-3">
            <Layers className="text-purple-400 size-7" />
            Control Deck
          </h1>
          <div className="flex items-center gap-3">
            <div className="text-right">
              <p className="text-sm font-bold text-white">{profile?.display_name || 'Pilot'}</p>
              <p className="text-[10px] text-slate-400 uppercase font-mono">{profile?.preferred_languages?.join(', ')}</p>
            </div>
            <div className="size-10 bg-[#121635] rounded-full overflow-hidden border border-purple-500/10">
              <img src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${profile?.id || 'AeroLearn'}`} alt="" />
            </div>
          </div>
        </header>

        {/* Dynamic Launch Workspaces Cards */}
        <section className="flex flex-col gap-4 relative z-10">
          <h3 className="font-extrabold text-lg text-white">Active Cockpits</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <button 
              onClick={() => onNavigate('blind')}
              className="flex p-6 rounded-2xl border border-yellow-400/20 bg-yellow-400/5 text-left hover:border-yellow-400 hover:bg-yellow-400/10 transition-all duration-300 group"
            >
              <div className="size-12 rounded-xl bg-yellow-400/10 border border-yellow-400/20 flex items-center justify-center mr-4">
                <Mic className="size-6 text-yellow-400" />
              </div>
              <div>
                <span className="font-extrabold text-lg text-yellow-300 block">Launch Blind Workspace</span>
                <span className="text-xs text-slate-300 leading-relaxed mt-1 block">Continuous microphone streaming audio command dashboard.</span>
              </div>
            </button>

            <button 
              onClick={() => onNavigate('deaf')}
              className="flex p-6 rounded-2xl border border-purple-500/20 bg-purple-500/5 text-left hover:border-purple-500 hover:bg-purple-500/10 transition-all duration-300 group"
            >
              <div className="size-12 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mr-4">
                <Accessibility className="size-6 text-purple-400" />
              </div>
              <div>
                <span className="font-extrabold text-lg text-purple-300 block">Launch Deaf Workspace</span>
                <span className="text-xs text-slate-300 leading-relaxed mt-1 block">Split-screen sign language video sync text highlighted reading deck.</span>
              </div>
            </button>
          </div>
        </section>

        {/* Document Status Listing */}
        <section className="flex flex-col gap-6 relative z-10">
          <h3 className="font-extrabold text-lg text-white">Your Study Documents ({documents.length})</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {documents.map(doc => (
              <GlassCard key={doc.id} className="p-6">
                <div className="flex justify-between items-start mb-4">
                  <div>
                    <h4 className="font-bold text-white text-md">{doc.title}</h4>
                    <span className="text-[10px] font-mono text-slate-400 uppercase">{doc.source_type} • {doc.target_lang}</span>
                  </div>
                  <span className={cn(
                    "text-[10px] font-mono uppercase px-2 py-0.5 rounded border",
                    doc.status === 'ready' ? "bg-emerald-500/15 border-emerald-500/35 text-emerald-400" :
                    doc.status === 'failed' ? "bg-rose-500/15 border-rose-500/35 text-rose-400" :
                    "bg-amber-500/15 border-amber-500/35 text-amber-400"
                  )}>
                    {doc.status}
                  </span>
                </div>
                {doc.status === 'ready' && (
                  <button 
                    onClick={() => onNavigate(`reader:${doc.id}`)}
                    className="w-full mt-2 py-2 bg-purple-600/20 hover:bg-purple-600 border border-purple-500/30 text-white font-bold text-xs uppercase rounded-lg transition-all"
                  >
                    Open Document
                  </button>
                )}
              </GlassCard>
            ))}
            {documents.length === 0 && (
              <p className="text-xs italic text-slate-500 col-span-2">No documents uploaded. Navigate to Ingestion Lab to begin.</p>
            )}
          </div>
        </section>
      </main>
    </div>
  );
};

// --- App Root Routing ---
export default function App() {
  const [screen, setScreen] = useState('login');
  const { profile, setProfile, loading } = useAccessibility();
  
  // Custom onboarding parameters state
  const [preferredLanguages, setPreferredLanguages] = useState([]);
  const [disabilities, setDisabilities] = useState([]);

  // Check auth state
  useEffect(() => {
    async function checkAuth() {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        // Fetch preferences
        const { data: prof } = await supabase.from('profiles').select('*').eq('id', session.user.id).single();
        if (prof && prof.preferred_languages && prof.preferred_languages.length > 0) {
          setScreen('dashboard');
        } else {
          setScreen('reg0');
        }
      } else {
        setScreen('login');
      }
    }
    checkAuth();
  }, []);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    setScreen('login');
  };

  const handleOnboardingComplete = () => {
    // Refresh accessibility context profile values
    window.location.reload();
  };

  return (
    <div className="min-h-screen">
      <AnimatePresence mode="wait">
        <motion.div
          key={screen}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          transition={{ duration: 0.25 }}
        >
          {screen === 'login' && <LoginScreen onNext={() => setScreen('reg0')} />}
          {screen === 'reg0' && <OnboardingStep0 onNext={() => setScreen('reg1')} />}
          {screen === 'reg1' && <OnboardingStep1 onNext={() => setScreen('reg2')} preferredLanguages={preferredLanguages} setPreferredLanguages={setPreferredLanguages} />}
          {screen === 'reg2' && <OnboardingStep2 onNext={() => setScreen('reg3')} disabilities={disabilities} setDisabilities={setDisabilities} />}
          {screen === 'reg3' && <OnboardingStep3 onNext={() => setScreen('reg4')} disabilities={disabilities} />}
          {screen === 'reg4' && <OnboardingStep4 onComplete={handleOnboardingComplete} preferredLanguages={preferredLanguages} disabilities={disabilities} />}
          
          {screen === 'dashboard' && (
            <StandardDashboard 
              profile={profile} 
              onNavigate={(s) => setScreen(s)} 
              onLogout={handleLogout} 
            />
          )}

          {screen === 'lab' && <DocumentLab onBack={() => setScreen('dashboard')} profile={profile} />}
          {screen === 'blind' && <BlindWorkspace onBack={() => setScreen('dashboard')} profile={profile} />}
          {screen === 'deaf' && <DeafWorkspace onBack={() => setScreen('dashboard')} />}
          {screen === 'hive' && <HiveFeed onBack={() => setScreen('dashboard')} onOpenDocument={(id) => setScreen(`reader:${id}`)} />}
          
          {screen.startsWith('reader:') && (
            <DocumentReader 
              documentId={screen.split(':')[1]} 
              onBack={() => setScreen('dashboard')} 
            />
          )}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
