'use client';

import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import {
  ArrowLeft,
  ArrowRight,
  Search,
  Mail,
  Key,
  LogIn,
  UserCircle,
  Settings,
  LayoutDashboard,
  FileText,
  Upload,
  BookOpen,
  Layers,
  Accessibility,
  Globe,
  Cpu,
  Wifi,
  UploadCloud,
  CheckCircle2,
  Radar,
  Database,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  Zap,
  Star,
  Filter,
  ChevronDown,
  Monitor,
  Smartphone,
  Info
} from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { supabase } from '@/lib/supabaseClient';
import { useAccessibility } from '@/context/AccessibilityContext';
import NeuralConstellationMap from '@/components/shared/NeuralConstellationMap';

function cn(...inputs) {
  return twMerge(clsx(inputs));
}

// --- Components ---

const GlassCard = ({ children, className, active, onClick }) => (
  <div
    onClick={onClick}
    className={cn(
      "p-6 rounded-2xl border backdrop-blur-xl transition-all duration-300",
      active
        ? "border-sky-500 bg-sky-500/10 shadow-[0_0_15px_rgba(14,165,233,0.2)]"
        : "border-slate-200 dark:border-slate-800 bg-white/5 hover:bg-white/10 dark:hover:bg-slate-900/40",
      className
    )}
  >
    {children}
  </div>
);

const CyberButton = ({
  children,
  variant = 'primary',
  className,
  onClick,
  icon: Icon,
  type = 'button',
  disabled = false
}) => {
  const variants = {
    primary: "bg-sky-600 hover:bg-sky-500 text-white shadow-lg shadow-sky-500/20 hover:shadow-sky-500/30",
    secondary: "bg-slate-800 text-slate-100 hover:bg-slate-700",
    ghost: "bg-transparent text-slate-300 hover:bg-white/5",
    outline: "border border-sky-500/50 text-sky-400 hover:bg-sky-500/10"
  };

  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled}
      className={cn(
        "px-6 py-2.5 uppercase tracking-wider font-bold text-xs rounded-xl transition-all duration-200 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed",
        variants[variant],
        className
      )}
    >
      {children}
      {Icon && <Icon className="size-4" />}
    </button>
  );
};

const ProgressIndicator = ({ phase, label, progress }) => (
  <section className="flex flex-col gap-4">
    <div className="flex justify-between items-end">
      <div>
        <p className="font-mono text-sky-400 uppercase tracking-widest mb-1 text-xs">{phase}</p>
        <h2 className="text-3xl font-extrabold text-white">{label}</h2>
      </div>
      <span className="font-mono text-slate-400 text-sm">{progress}%</span>
    </div>
    <div className="flex h-1 gap-2 w-full bg-slate-800 rounded-full overflow-hidden">
      <div
        className="bg-sky-500 shadow-[0_0_10px_rgba(14,165,233,0.5)] transition-all duration-500 rounded-full"
        style={{ width: `${progress}%` }}
      />
    </div>
  </section>
);

// --- Screens ---

const LoginScreen = ({ onNext }) => {
  const { setProfile } = useAccessibility();
  const [isSignUp, setIsSignUp] = useState(false);
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [fullName, setFullName] = useState('');

  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  const handleAuthSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setErrorMsg('');
    setSuccessMsg('');

    try {
      if (isSignUp) {
        if (!fullName.trim()) {
          throw new Error('Please enter your name to proceed.');
        }

        const { data, error: signUpError } = await supabase.auth.signUp({
          email,
          password,
          options: {
            data: {
              full_name: fullName.trim()
            }
          }
        });

        if (signUpError) throw signUpError;

        if (!data?.user) {
          throw new Error('Registration completed, but session is not established yet.');
        }

        // Fetch the profile that was auto-generated by the database trigger
        const { data: profileData } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', data.user.id)
          .single();

        if (profileData) {
          setProfile(profileData);
        }

        setSuccessMsg("Account created successfully! Let's choose your settings...");
        setTimeout(() => {
          onNext();
        }, 1200);
      } else {
        const { data, error: loginError } = await supabase.auth.signInWithPassword({
          email,
          password,
        });

        if (loginError) throw loginError;

        if (!data?.user) {
          throw new Error('Failed to retrieve active user session.');
        }

        const { data: profileData } = await supabase
          .from('profiles')
          .select('*')
          .eq('id', data.user.id)
          .single();

        if (profileData) {
          setProfile(profileData);
        }

        setSuccessMsg('Successfully logged in! Opening your classroom...');
        setTimeout(() => {
          onNext();
        }, 1200);
      }
    } catch (err) {
      console.error(err);
      setErrorMsg(err.message || 'Login failed. Please check your spelling and password.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center p-4 relative bg-[#0c0f24] text-slate-100 overflow-hidden">
      <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(168,85,247,0.12)_0%,transparent_70%)] pointer-events-none" />

      <GlassCard className="w-full max-w-[480px] p-8 md:p-10 flex flex-col gap-6 border-purple-500/10 bg-[#121635]/60 levitate">
        <div className="flex flex-col items-center gap-3">
          <div className="flex items-center gap-3 text-purple-400">
            <Zap className="size-10 fill-purple-400/20" />
            <h1 className="text-3xl font-extrabold tracking-tight">AeroLearn</h1>
          </div>
          <p className="text-slate-300 text-sm">Welcome, Space Explorer! 💫</p>
        </div>

        {errorMsg && (
          <div role="alert" className="p-3.5 rounded-xl border border-rose-500/20 bg-rose-500/10 text-rose-300 text-xs">
            ⚠️ {errorMsg}
          </div>
        )}

        {successMsg && (
          <div role="alert" className="p-3.5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 text-emerald-300 text-xs">
            ✓ {successMsg}
          </div>
        )}

        <form onSubmit={handleAuthSubmit} className="flex flex-col gap-5">
          {isSignUp && (
            <div className="flex flex-col gap-2">
              <label htmlFor="name-input" className="text-xs font-bold text-purple-300 flex items-center gap-2">
                <div className="w-1.5 h-3.5 bg-purple-500 rounded-full" />
                Your Name
              </label>
              <input
                id="name-input"
                type="text"
                required
                disabled={loading}
                value={fullName}
                onChange={(e) => setFullName(e.target.value)}
                placeholder="Write your name here"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          )}

          <div className="flex flex-col gap-2">
            <label htmlFor="email-input" className="text-xs font-bold text-purple-300 flex items-center gap-2">
              <div className="w-1.5 h-3.5 bg-purple-500 rounded-full" />
              Your Email Address ✉️
            </label>
            <div className="relative">
              <Mail className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-purple-300/60" />
              <input
                id="email-input"
                type="email"
                required
                disabled={loading}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="name@email.com"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 pl-12 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          </div>

          <div className="flex flex-col gap-2">
            <div className="flex justify-between items-center">
              <label htmlFor="pass-input" className="text-xs font-bold text-purple-300 flex items-center gap-2">
                <div className="w-1.5 h-3.5 bg-purple-500 rounded-full" />
                Your Secret Password 🔑
              </label>
            </div>
            <div className="relative">
              <Key className="absolute left-4 top-1/2 -translate-y-1/2 size-4 text-purple-300/60" />
              <input
                id="pass-input"
                type="password"
                required
                disabled={loading}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="••••••••••••"
                className="w-full bg-[#0b0d19]/80 border-2 border-purple-500/10 p-3.5 pl-12 rounded-2xl focus:outline-none focus:ring-2 focus:ring-purple-400 text-sm text-white"
              />
            </div>
          </div>

          <CyberButton type="submit" disabled={loading} className="w-full mt-2 bouncy-pill bg-purple-600 hover:bg-purple-500" icon={LogIn}>
            {loading ? 'Opening Your Space... 🚀' : isSignUp ? 'Sign Up & Start! 🚀' : 'Login & Start! 🚀'}
          </CyberButton>
        </form>

        <div className="flex items-center gap-4">
          <div className="flex-1 h-px bg-purple-500/10" />
          <span className="text-xs font-bold text-purple-300/40">Welcome! 🌟</span>
          <div className="flex-1 h-px bg-purple-500/10" />
        </div>

        <p className="text-center text-sm text-slate-300">
          {isSignUp ? 'Already registered?' : 'New here?'}
          <button
            type="button"
            onClick={() => {
              setIsSignUp(!isSignUp);
              setErrorMsg('');
              setSuccessMsg('');
            }}
            className="text-purple-400 hover:underline font-bold ml-2"
          >
            {isSignUp ? 'Login Here 🔑' : 'Create Account 🚀'}
          </button>
        </p>
      </GlassCard>
    </div>
  );
};

const Registration0 = ({ onNext }) => (
  <div className="min-h-screen flex items-center justify-center p-4 bg-[#0c0f24] text-slate-100">
    <div className="w-full max-w-[640px] flex flex-col gap-10">
      <ProgressIndicator phase="Step 1: Your Account 🌟" label="Account Settings" progress={25} />

      <GlassCard className="p-6 md:p-10 flex flex-col gap-8 bg-[#121635]/60 border-purple-500/10 levitate">
        <p className="text-slate-200 text-base leading-relaxed">
          Welcome! Your account is created. Now we will choose the best settings to make reading, listening, and learning super easy and fun for you!
        </p>

        <div className="flex justify-between items-center pt-6 border-t border-purple-500/10">
          <CyberButton variant="ghost" className="bouncy-pill">Go Back ⬅️</CyberButton>
          <CyberButton onClick={onNext} icon={ArrowRight} className="bouncy-pill bg-purple-600 hover:bg-purple-500">Let's Start! 🚀</CyberButton>
        </div>
      </GlassCard>
    </div>
  </div>
);

const Registration1 = ({ onNext }) => (
  <div className="max-w-[800px] mx-auto py-16 px-4 flex flex-col gap-12 text-slate-100">
    <ProgressIndicator phase="Step 2: Your Language 🗣️" label="Choose Your Language" progress={50} />
    <p className="text-lg text-slate-300 -mt-6">Choose the language you speak best so we can translate books and videos for you.</p>

    <div className="flex flex-col gap-4">
      <label className="text-sm font-bold text-purple-300">Search for your language:</label>
      <div className="relative">
        <Search className="absolute left-4 top-1/2 -translate-y-1/2 size-5 text-purple-300/60" />
        <input
          type="text"
          placeholder="e.g., English, Spanish, ASL"
          className="w-full bg-[#121635]/80 border-2 border-purple-500/10 rounded-2xl p-4 pl-12 focus:outline-none focus:ring-2 focus:ring-purple-400 text-white"
        />
      </div>
    </div>

    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between border-b border-purple-500/10 pb-2">
        <h2 className="text-xl font-bold">Choose Your Language:</h2>
        <span className="text-[10px] bg-purple-500/20 text-purple-300 border border-purple-500/30 px-2.5 py-1 uppercase font-mono rounded-lg">Required</span>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {['English (en)', 'Spanish (es)', 'French (fr)', 'German (de)', 'Japanese (ja)', 'Chinese (zh)'].map((lang, i) => (
          <button
            key={lang}
            className={cn(
              "p-5 text-left rounded-2xl border-2 transition-all duration-200 bouncy-pill",
              i === 0
                ? "border-purple-500 bg-purple-500/10 text-white"
                : "border-purple-500/10 bg-[#121635]/40 text-slate-300 hover:border-purple-400/50"
            )}
          >
            {lang}
          </button>
        ))}
      </div>
    </div>

    <div className="flex justify-between items-center pt-8 border-t border-purple-500/10 mt-auto">
      <p className="text-xs text-slate-400 max-w-sm">Language settings configure translation engines across the document parser modules.</p>
      <CyberButton onClick={onNext} icon={ArrowRight} className="bouncy-pill bg-purple-600 hover:bg-purple-500">Save and Continue ➡️</CyberButton>
    </div>
  </div>
);

const Registration2 = ({ onNext, profile, togglePreference }) => {
  return (
    <div className="max-w-[640px] mx-auto py-16 px-4 flex flex-col gap-12 text-slate-100">
      <ProgressIndicator phase="Step 3: Easy Reading Settings 🌈" label="Easy Reading Settings" progress={75} />
      <p className="text-slate-300 text-lg -mt-6">Choose how you want to read. We can change the text layout, font size, and contrast to make it super easy for you to see and learn.</p>

      <div className="flex flex-col gap-4">
        {/* Dyslexia Accommodations Switch */}
        <GlassCard
          active={profile.dyslexia_friendly}
          onClick={() => togglePreference('dyslexia_friendly', profile.dyslexia_friendly)}
          className="p-6 cursor-pointer border-purple-500/10 bg-[#121635]/60 hover:border-purple-400/30"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className={cn("size-10 rounded-full flex items-center justify-center", profile.dyslexia_friendly ? "bg-purple-500/20 text-purple-400" : "bg-[#0b0d19] text-slate-400")}>
                <Zap className="size-6" />
              </div>
              <div>
                <span className="text-lg font-bold block">Special Dyslexia Font 📖</span>
                <span className="text-xs text-slate-300 mt-1 block">Makes letters easier to read so they don't jump around on the screen.</span>
              </div>
            </div>
            <div className={cn("w-10 h-5 rounded-full relative transition-colors", profile.dyslexia_friendly ? "bg-purple-500" : "bg-slate-700")}>
              <div className={cn("absolute top-1 size-3 bg-white rounded-full transition-all", profile.dyslexia_friendly ? "right-1" : "left-1")} />
            </div>
          </div>
        </GlassCard>

        {/* High Contrast Accommodations Switch */}
        <GlassCard
          active={profile.high_contrast}
          onClick={() => togglePreference('high_contrast', profile.high_contrast)}
          className="p-6 cursor-pointer border-purple-500/10 bg-[#121635]/60 hover:border-purple-400/30"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className={cn("size-10 rounded-full flex items-center justify-center", profile.high_contrast ? "bg-purple-500/20 text-purple-400" : "bg-[#0b0d19] text-slate-400")}>
                <Accessibility className="size-6" />
              </div>
              <div>
                <span className="text-lg font-bold block">Super Bright Contrast 🎨</span>
                <span className="text-xs text-slate-300 mt-1 block">Makes text pop out clearly against the background for easy reading.</span>
              </div>
            </div>
            <div className={cn("w-10 h-5 rounded-full relative transition-colors", profile.high_contrast ? "bg-purple-500" : "bg-slate-700")}>
              <div className={cn("absolute top-1 size-3 bg-white rounded-full transition-all", profile.high_contrast ? "right-1" : "left-1")} />
            </div>
          </div>
        </GlassCard>

        {/* Deaf / Hard of Hearing preference */}
        <GlassCard
          active={profile.sign_language_preference}
          onClick={() => togglePreference('sign_language_preference', profile.sign_language_preference)}
          className="p-6 cursor-pointer border-purple-500/10 bg-[#121635]/60 hover:border-purple-400/30"
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className={cn("size-10 rounded-full flex items-center justify-center", profile.sign_language_preference ? "bg-purple-500/20 text-purple-400" : "bg-[#0b0d19] text-slate-400")}>
                <Globe className="size-6" />
              </div>
              <div>
                <span className="text-lg font-bold block">Sign Language Helpers 🤟</span>
                <span className="text-xs text-slate-300 mt-1 block">Adds a friendly virtual sign language helper next to videos.</span>
              </div>
            </div>
            <div className={cn("w-10 h-5 rounded-full relative transition-colors", profile.sign_language_preference ? "bg-purple-500" : "bg-slate-700")}>
              <div className={cn("absolute top-1 size-3 bg-white rounded-full transition-all", profile.sign_language_preference ? "right-1" : "left-1")} />
            </div>
          </div>

          {profile.sign_language_preference && (
            <motion.div
              initial={{ height: 0, opacity: 0 }}
              animate={{ height: 'auto', opacity: 1 }}
              className="mt-6 pt-6 border-t border-purple-500/20 flex flex-col gap-6"
              onClick={(e) => e.stopPropagation()}
            >
              <p className="text-slate-300 text-xs">Choose your sign language style:</p>

              <div className="flex flex-col gap-3">
                <span className="text-xs font-bold text-purple-300">Sign Language Variant</span>
                <div className="flex flex-wrap gap-2">
                  {['ASL (American)', 'BSL (British)', 'ISL (Irish)'].map((l, i) => (
                    <button
                      key={l}
                      className={cn("px-4 py-2 text-xs border rounded-lg bouncy-pill", i === 0 ? "border-purple-500 bg-purple-500/20 text-purple-400" : "border-purple-500/10 text-slate-300")}
                    >
                      {l}
                    </button>
                  ))}
                </div>
              </div>
            </motion.div>
          )}
        </GlassCard>
      </div>

      <CyberButton className="w-full mt-4 bouncy-pill bg-purple-600 hover:bg-purple-500" onClick={onNext}>
        Go to Dashboard 🚀
      </CyberButton>
    </div>
  );
};

const Registration3 = ({ onNext, onPrev, profile, togglePreference }) => (
  <div className="max-w-[800px] mx-auto py-16 px-4 flex flex-col gap-12 text-slate-100">
    <ProgressIndicator phase="Step 4: Screen Settings 📺" label="Screen & Device Settings" progress={100} />
    <p className="text-lg text-slate-300 -mt-6">Choose your screen type and speed options so the system works best on your device.</p>

    <form className="flex flex-col gap-12" onSubmit={(e) => { e.preventDefault(); onNext(); }}>
      <div className="flex flex-col gap-4">
        <label className="text-sm font-bold text-purple-300">What device are you using?</label>
        <div className="relative">
          <select className="w-full bg-[#121635] border border-purple-500/10 text-white p-4 rounded-2xl appearance-none focus:ring-2 focus:ring-purple-400 focus:outline-none transition-all">
            <option>Computer or Laptop 💻</option>
            <option>Mobile Phone or Tablet 📱</option>
          </select>
          <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none text-purple-300" />
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <label className="text-sm font-bold text-purple-300">Internet Sync Style:</label>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <GlassCard active className="p-6 cursor-pointer flex gap-4 border-purple-500/30 bg-[#121635]/80 hover:border-purple-400/50">
            <div className="size-5 rounded-full border-2 border-purple-500 flex items-center justify-center"><div className="size-2.5 bg-purple-500 rounded-full" /></div>
            <div>
              <h4 className="font-bold">Fast Video Sync ⚡</h4>
              <p className="text-sm text-slate-300 mt-1">Best for high-speed internet. Shows everything instantly.</p>
            </div>
          </GlassCard>
          <GlassCard className="p-6 cursor-pointer flex gap-4 border-purple-500/10 bg-[#121635]/40 hover:border-purple-400/50">
            <div className="size-5 rounded-full border-2 border-purple-500/20" />
            <div>
              <h4 className="font-bold">Saver Sync Mode 💾</h4>
              <p className="text-sm text-slate-300 mt-1">Best for slower internet. Saves your internet data.</p>
            </div>
          </GlassCard>
        </div>
      </div>

      <div className="flex flex-col gap-4">
        <label className="text-sm font-bold text-purple-300">Boost Screen Brightness:</label>
        <div className="flex flex-col gap-4">
          <GlassCard className="p-6 flex items-center justify-between border-purple-500/10 bg-[#121635]/60 hover:border-purple-400/30" onClick={() => togglePreference('high_contrast', profile.high_contrast)}>
            <div className="pr-4">
              <h4 className="font-bold">Boost Screen Brightness 🌟</h4>
              <p className="text-sm text-slate-300 mt-1">Makes the screen extra clear and easy to read.</p>
            </div>
            <div className={cn("w-10 h-5 rounded-full relative transition-colors", profile.high_contrast ? "bg-purple-500" : "bg-slate-700")}>
              <div className={cn("absolute top-1 size-3 bg-white rounded-full transition-all", profile.high_contrast ? "right-1" : "left-1")} />
            </div>
          </GlassCard>
        </div>
      </div>

      <div className="flex justify-between items-center mt-8 pt-8 border-t border-purple-500/10">
        <CyberButton variant="outline" onClick={onPrev} className="bouncy-pill">Go Back ⬅️</CyberButton>
        <CyberButton type="submit" className="bouncy-pill bg-purple-600 hover:bg-purple-500">All Done! Let's Enter! 🎉</CyberButton>
      </div>
    </form>
  </div>
);

const Dashboard = ({ onNavigate, profile }) => {
  const handleLogout = async () => {
    await supabase.auth.signOut();
    window.location.reload();
  };

  return (
    <div className="flex h-screen bg-[#0c0f24] text-white overflow-hidden">
      {/* Sidebar */}
      <aside className="w-[280px] bg-[#121635] border-r border-purple-500/10 p-6 flex flex-col gap-10">
        <div className="flex items-center gap-3">
          <div className="size-10 bg-purple-500/10 rounded-xl border border-purple-500/20 flex items-center justify-center">
            <Zap className="size-6 text-purple-400 fill-purple-400/20" />
          </div>
          <div>
            <h2 className="font-extrabold text-white text-lg leading-tight">AeroLearn</h2>
            <p className="text-[10px] text-purple-300/60 font-mono tracking-wider uppercase">AI-Powered Adaptive Learning Control Deck</p>
          </div>
        </div>

        <nav className="flex flex-col gap-2">
          {[
            { icon: LayoutDashboard, label: 'Control Deck', active: true },
            { icon: FileText, label: 'Document Lab', onClick: () => onNavigate('uploads') },
            { icon: PlayCircle, label: 'YouTube Ingest', onClick: () => onNavigate('media') },
            { icon: BookOpen, label: 'Speech Transcript', onClick: () => onNavigate('player') },
            { icon: Globe, label: 'Social Notes Hive', onClick: () => onNavigate('hive') },
            { icon: Settings, label: 'System Config', onClick: () => onNavigate('settings') }
          ].map(item => (
            <button
              key={item.label}
              onClick={item.onClick}
              className={cn(
                "flex items-center gap-4 px-4 py-3 rounded-xl transition-all cursor-pointer font-bold text-sm text-left border-l-4 bouncy-pill",
                item.active
                  ? "bg-purple-500/10 text-purple-400 border-l-purple-500"
                  : "text-slate-300 border-l-transparent hover:bg-white/5 hover:text-white"
              )}
            >
              <item.icon className="size-5" />
              <span>{item.label}</span>
            </button>
          ))}
        </nav>

        <div className="mt-auto pt-6 border-t border-purple-500/10">
          <button
            onClick={handleLogout}
            className="w-full py-2.5 bg-[#0b0d19] hover:bg-rose-500/10 text-slate-300 hover:text-rose-400 border border-purple-500/10 hover:border-rose-500/20 text-xs font-bold uppercase rounded-xl transition-all bouncy-pill"
          >
            Clear clearances (Log Out)
          </button>
        </div>
      </aside>

      {/* Main Panel */}
      <main className="flex-1 overflow-y-auto p-10 flex flex-col gap-10 relative">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(168,85,247,0.05)_0%,transparent_70%)] pointer-events-none" />

        <header className="flex justify-between items-center relative z-10">
          <h1 className="text-3xl font-extrabold flex items-center gap-3">
            <Layers className="text-purple-400 size-7" />
            AeroLearn Control Deck
          </h1>
          <div className="flex items-center gap-4">
            <div className="relative w-64">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-purple-300/60" />
              <input
                type="text"
                placeholder="Query system files..."
                className="w-full bg-[#121635] border border-purple-500/10 rounded-xl p-2 pl-10 text-xs focus:ring-2 focus:ring-purple-400 text-white"
              />
            </div>
            <div className="size-10 bg-[#121635] rounded-full overflow-hidden border border-purple-500/10">
              <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=AeroLearn" alt="Profile Avatar" />
            </div>
          </div>
        </header>

        <section className="flex items-center gap-6 bg-[#121635]/20 border border-purple-500/10 p-6 rounded-2xl relative z-10 levitate">
          <div className="size-24 rounded-full overflow-hidden border-4 border-purple-500/20 flex-shrink-0">
            <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=AeroLearn" alt="Profile" className="bg-[#121635]" />
          </div>
          <div>
            <h2 className="text-3xl font-extrabold text-white">Welcome back, Space Explorer! 💫</h2>
            <p className="text-slate-300 text-sm mt-1">AI-Powered Adaptive Learning Control Deck</p>
          </div>
        </section>

        {/* Dynamic Space Navigation Sections */}
        <section className="flex flex-col gap-4 relative z-10">
          <h3 className="font-extrabold text-lg text-white">Core Learning Spaces</h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {[
              {
                label: 'Document Processing Lab',
                desc: 'Ingest handwritten engineering lecture scans, textbook chapters, or technical papers to run instant structural text simplification and key terms mapping.',
                icon: UploadCloud,
                onClick: () => onNavigate('uploads')
              },
              {
                label: 'YouTube Video Ingestion Lab',
                desc: 'Paste any recorded classroom lecture video link to segment raw audio profiles, map semantic timestamps, and compile clean scannable notes blocks.',
                icon: PlayCircle,
                onClick: () => onNavigate('media')
              },
              {
                label: 'Live Speech Transcription Hub',
                desc: 'Stream real-time microphone arrays directly into local processing units to capture lecture speech and render immediate accessible transcript text overlays.',
                icon: Accessibility,
                onClick: () => onNavigate('player')
              }
            ].map(item => (
              <button
                key={item.label}
                onClick={item.onClick}
                className="flex flex-col p-6 rounded-2xl border border-purple-500/10 bg-[#121635]/30 text-left hover:border-purple-400/50 hover:bg-[#121635]/50 transition-all duration-300 group levitate"
              >
                <div className="size-12 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-center mb-4 group-hover:scale-105 transition-transform duration-200">
                  <item.icon className="size-6 text-purple-400" />
                </div>
                <span className="font-extrabold text-lg text-white block mb-2">{item.label}</span>
                <span className="text-xs text-slate-300 leading-relaxed block">{item.desc}</span>
              </button>
            ))}
          </div>
        </section>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 relative z-10">
          {/* Active Pathways */}
          <div className="flex flex-col gap-6 lg:col-span-2">
            <h3 className="font-extrabold text-lg text-white">Active Synapse Pathways</h3>
            <NeuralConstellationMap 
              onNodeClick={(node) => {
                console.log("Navigating to star node:", node);
                if (node.id === 'mod-1') onNavigate('uploads');
                else if (node.id === 'mod-2') onNavigate('notes');
                else if (node.id === 'mod-3') onNavigate('media');
                else if (node.id === 'mod-4') onNavigate('player');
                else if (node.id === 'mod-5') onNavigate('settings');
                else if (node.id === 'mod-6') onNavigate('hive');
              }}
            />
          </div>

          {/* System Feed */}
          <div className="flex flex-col gap-6 lg:col-span-2">
            <h3 className="font-extrabold text-lg text-white">AeroLearn Platform Feed</h3>
            <div className="flex items-center gap-4">
              <span className="px-3 py-1 rounded text-[10px] font-mono uppercase bg-sky-500/15 border-l-2 border-sky-500 text-sky-400">Activity Log</span>
            </div>
            <div className="flex flex-col gap-6 border-l border-slate-800 ml-2 pl-6">
              {[
                { time: '10 Mins Ago', icon: Cpu, content: 'Module <span class="text-sky-400 font-bold">F = ma Momentum</span> simplified and adapted to Tier: simplified.' },
                { time: '3 Hours Ago', icon: FileText, content: 'Document <span class="text-sky-400 font-bold">Inertial_Frames.pdf</span> processed by Ollama VLM fallback.' },
                { time: '1 Day Ago', icon: Settings, content: 'Accessibility accommodations toggled. Layout font scales updated.' }
              ].map((item, i) => (
                <div key={i} className="relative">
                  <div className={cn("absolute -left-[30px] top-1.5 size-2 rounded-full", i === 0 ? "bg-sky-500" : "bg-slate-700")} />
                  <div className="flex items-center gap-2 text-[10px] font-mono uppercase text-slate-500 mb-1">
                    <item.icon className="size-3.5" />
                    {item.time}
                  </div>
                  <p className="text-sm text-slate-300" dangerouslySetInnerHTML={{ __html: item.content }} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

const HiveScreen = ({ onBack }) => (
  <div className="min-h-screen bg-slate-950 text-white">
    <header className="border-b border-slate-800 p-6 flex justify-between items-center bg-slate-900/30">
      <div className="flex items-center gap-6">
        <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl"><ArrowLeft className="size-6 text-slate-400 hover:text-sky-400 transition-colors" /></button>
        <h1 className="text-2xl font-bold flex items-center gap-3">
          <Zap className="text-sky-400" />
          Social Knowledge Hive
        </h1>
      </div>
    </header>

    <div className="max-w-[1280px] mx-auto p-10 grid grid-cols-12 gap-10">
      <aside className="col-span-3 flex flex-col gap-8">
        <div className="flex flex-col gap-4">
          <h3 className="text-xs font-mono uppercase tracking-widest text-slate-500">Search Knowledge</h3>
          <div className="relative">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-sky-400" />
            <input type="text" placeholder="Keywords, fields..." className="w-full bg-slate-900 border border-slate-800 rounded-xl p-2.5 pl-10 text-sm focus:ring-1 focus:ring-sky-500 text-white focus:outline-none" />
          </div>
        </div>

        <div className="flex flex-col gap-6 p-6 rounded-2xl border border-slate-800 bg-slate-900/20">
          <h3 className="text-lg font-bold flex items-center gap-2 text-sky-400">
            <Filter className="size-5" />
            Adaptive Toggles
          </h3>
          <div className="flex flex-col gap-4">
            {['Dyslexia-Optimized', 'Deaf-Friendly Captioning', 'Mobility Grids', 'Low-Sensory Tiers'].map((f, i) => (
              <label key={f} className="flex items-center gap-3 cursor-pointer group">
                <input type="checkbox" checked={i === 1} className="size-4 bg-slate-900 border-slate-700 text-sky-500 focus:ring-sky-500" readOnly />
                <span className={cn("text-sm transition-colors", i === 1 ? "text-sky-400" : "text-slate-400 group-hover:text-white")}>{f}</span>
              </label>
            ))}
          </div>
          <div className="h-px bg-slate-800 w-full" />
          <h3 className="text-lg font-bold flex items-center gap-2 text-sky-400">
            <Globe className="size-5" />
            Linguistic Roots
          </h3>
          <div className="flex flex-wrap gap-2">
            {['English', 'Spanish', 'ASL'].map((l, i) => (
              <button key={l} className={cn("px-3 py-1.5 rounded-lg text-xs border border-l-4 font-bold", i === 1 ? "border-sky-500/30 bg-sky-500/10 border-l-sky-500 text-sky-400" : "border-slate-800 border-l-slate-600 text-slate-400")}>{l}</button>
            ))}
          </div>
        </div>
      </aside>

      <section className="col-span-9 flex flex-col gap-8">
        <div className="flex justify-between items-center">
          <p className="text-slate-400">Showing <span className="text-white font-extrabold">124</span> community summaries</p>
          <button className="flex items-center gap-2 text-sky-400 font-bold text-sm">Sort by: Recent <ChevronDown className="size-4" /></button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            { title: 'Classical Inertial Frames Physics Pathways', rating: '4.8', tags: ['STEM', 'English'], desc: 'Simplifications for linear transformations and vector sums.' },
            { title: 'Quantum Computing Sensory Tiers', rating: '4.5', tags: ['Low-Sensory', 'Spanish'], desc: 'Step-by-step mathematical procedures containing no visual clutter.', active: true },
            { title: 'Neural Systems Audio Maps', rating: '4.9', tags: ['Deaf-Friendly', 'English'], desc: 'Interactive transcripts mapped directly to key visual frames.' }
          ].map((note, i) => (
            <GlassCard key={i} className={cn("group cursor-pointer flex flex-col p-0 overflow-hidden", note.active && "border-sky-500")}>
              <div className="aspect-video bg-slate-900 relative overflow-hidden">
                <img src={`https://picsum.photos/seed/${i + 20}/400/225`} alt="" className="w-full h-full object-cover opacity-60 group-hover:opacity-100 transition-all duration-300" />
                <div className="absolute top-2 right-2 bg-slate-950/80 backdrop-blur px-2.5 py-1 text-[10px] font-bold rounded flex items-center gap-1"><Star className="size-3 text-yellow-400 fill-yellow-400" /> {note.rating}</div>
              </div>
              <div className="p-5 flex flex-col gap-3 flex-1 bg-slate-900/30">
                <h4 className="font-bold group-hover:text-sky-400 transition-colors duration-200">{note.title}</h4>
                <p className="text-xs text-slate-400 line-clamp-2 leading-relaxed">{note.desc}</p>
                <div className="flex gap-2 mt-auto">
                  {note.tags.map(t => <span key={t} className="text-[10px] uppercase font-mono border-l-2 border-sky-500 pl-2 text-slate-400">{t}</span>)}
                </div>
              </div>
            </GlassCard>
          ))}
        </div>
      </section>
    </div>
  </div>
);

const UploadCockpit = ({ onBack }) => {
  const { profile } = useAccessibility();
  const [files] = useState([
    { name: 'Inertial_Frames_Draft.pdf', size: '2.4 MB', status: 'Synthesized', progress: 100 },
    { name: 'Classical_Mechanics_Formulas.docx', size: '1.8 MB', status: 'Ingesting', progress: 65 },
    { name: 'AeroLearn_Quantum_Study.txt', size: '45 KB', status: 'Queued', progress: 0 }
  ]);
  const [uploadedFile, setUploadedFile] = useState(null);
  const [documentNotes, setDocumentNotes] = useState('');
  const [docLoading, setDocLoading] = useState(false);
  const [docError, setDocError] = useState('');
  const [docSuccess, setDocSuccess] = useState(false);

  const handleDocumentUpload = async (fileToUpload) => {
    if (!fileToUpload) return;
    setUploadedFile(fileToUpload);
    setDocLoading(true);
    setDocError('');
    setDocSuccess(false);
    setDocumentNotes('');

    const formData = new FormData();
    formData.append('file', fileToUpload);
    formData.append('userId', profile?.id || 'explorer_child_123');

    try {
      const response = await fetch('http://127.0.0.1:8000/api/process-document', {
        method: 'POST',
        body: formData,
      });
      if (!response.ok) {
        throw new Error(`Failed with status: ${response.status}`);
      }
      const result = await response.json();
      if (result.status === 'success') {
        setDocSuccess(true);
        setDocumentNotes(result.data.adapted_markdown);
      } else {
        throw new Error(result.message || 'Verification failed');
      }
    } catch (err) {
      console.error(err);
      if (err.message && (err.message.includes('Failed to fetch') || err.message.includes('NetworkError'))) {
        setDocError('Connection refused: Could not connect to the AeroLearn Core Engine. Please verify the backend is running locally on port 8000.');
      } else {
        setDocError(err.message || 'An error occurred during document ingestion');
      }
    } finally {
      setDocLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0c0f24] text-white flex flex-col">
      <header className="border-b border-purple-500/10 p-6 flex justify-between items-center bg-[#121635]/30">
        <div className="flex items-center gap-6">
          <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl cursor-pointer"><ArrowLeft className="size-6 text-slate-400 hover:text-purple-400 transition-colors" /></button>
          <h1 className="text-2xl font-bold flex items-center gap-3">
            <UploadCloud className="text-purple-400" />
            Document Processing Lab
          </h1>
        </div>
      </header>

      <div className="max-w-[1000px] mx-auto w-full p-10 flex flex-col gap-10">
        <div className="flex flex-col gap-4">
          <h2 className="text-lg font-bold">Ingest Academic Materials</h2>
          <label htmlFor="file-selector" className="border-2 border-dashed border-purple-500/10 p-16 flex flex-col items-center justify-center gap-6 rounded-2xl bg-[#121635]/10 hover:border-purple-400 transition-all cursor-pointer group levitate relative">
            <input
              type="file"
              id="file-selector"
              className="hidden"
              onChange={(e) => {
                if (e.target.files && e.target.files[0]) {
                  handleDocumentUpload(e.target.files[0]);
                }
              }}
            />
            <div className="size-20 rounded-full bg-[#121635] border border-purple-500/10 flex items-center justify-center group-hover:bg-purple-500/10 transition-colors">
              <UploadCloud className="size-10 text-purple-300/60 group-hover:text-purple-400 transition-colors" />
            </div>
            <div className="text-center">
              <p className="text-xl font-bold">Upload Academic PDF or Image Asset</p>
              <p className="text-purple-300/60 text-sm mt-1">Drag and drop your file here or click below to browse</p>
            </div>
            <div className="bouncy-pill py-2.5 px-6 rounded-xl bg-purple-500/10 text-purple-400 border border-purple-500/20 text-xs font-bold uppercase transition-all">
              Select Academic File
            </div>
          </label>
        </div>

        {docLoading && (
          <div className="flex flex-col items-center justify-center p-8 border border-purple-500/10 rounded-2xl bg-[#121635]/20 levitate">
            <div className="size-10 border-4 border-purple-500/20 border-t-purple-500 rounded-full animate-spin mb-4" />
            <p className="text-purple-300 font-bold text-sm">Processing document nodes and OCR elements... 🚀</p>
          </div>
        )}

        {docError && (
          <div className="p-4 border border-rose-500/20 rounded-xl bg-rose-500/10 text-rose-400 text-sm">
            ⚠️ {docError}
          </div>
        )}

        {docSuccess && (
          <div className="p-6 border border-purple-500/30 rounded-2xl bg-[#121635]/45 levitate">
            <div className="flex items-center gap-3 text-purple-400 font-bold text-lg mb-2">
              <CheckCircle2 className="size-6 text-green-400" />
              Document Simplification Complete! 🎉
            </div>
            <p className="text-xs text-slate-400 font-mono mb-4">Ingested file: <span className="text-white font-extrabold">{uploadedFile?.name}</span></p>
            <div className="bg-[#0c0f24] border border-purple-500/10 rounded-xl p-6 text-slate-200 text-sm font-sans leading-relaxed prose prose-invert max-w-none">
              <ReactMarkdown>{documentNotes}</ReactMarkdown>
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
          <div className="md:col-span-2 flex flex-col gap-6">
            <h3 className="font-bold flex items-center justify-between">
              Active Documents
              <span className="text-xs font-mono text-slate-500">{files.length} ITEMS</span>
            </h3>
            <div className="flex flex-col gap-4">
              {files.map((file, i) => (
                <GlassCard key={i} className="p-6">
                  <div className="flex items-start justify-between mb-4">
                    <div className="flex items-center gap-4">
                      <div className="size-12 bg-slate-900 border border-slate-800 rounded-xl flex items-center justify-center">
                        <FileText className={cn("size-6", file.progress === 100 ? "text-sky-400" : "text-slate-500")} />
                      </div>
                      <div>
                        <h4 className="font-bold">{file.name}</h4>
                        <p className="text-xs text-slate-500 font-mono mt-1">{file.size} • {file.status.toUpperCase()}</p>
                      </div>
                    </div>
                    {file.progress === 100 ? (
                      <CheckCircle2 className="size-6 text-sky-400" />
                    ) : (
                      <div className="size-5 border-2 border-sky-500/20 border-t-sky-500 rounded-full animate-spin" />
                    )}
                  </div>
                  <div className="h-1 bg-slate-800 w-full rounded-full overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${file.progress}%` }}
                      className="h-full bg-sky-500 shadow-[0_0_8px_rgba(14,165,233,0.5)] transition-all"
                    />
                  </div>
                </GlassCard>
              ))}
            </div>
          </div>

          <aside className="flex flex-col gap-8">
            <div className="flex flex-col gap-6 p-6 rounded-2xl border border-slate-800 bg-[#121635]/20">
              <h3 className="font-bold text-purple-400 flex items-center gap-2">
                <Settings className="size-5" />
                Processing Protocols
              </h3>

              <div className="flex flex-col gap-4">
                <div className="flex flex-col gap-2">
                  <span className="text-[10px] font-mono uppercase text-slate-500">Target Language</span>
                  <select className="bg-slate-900 border border-slate-800 rounded-lg p-2.5 text-sm text-white focus:outline-none focus:ring-1 focus:ring-sky-500">
                    <option>Auto-Detect Context</option>
                    <option>English</option>
                    <option>Spanish</option>
                  </select>
                </div>

                <div className="flex flex-col gap-2">
                  <span className="text-[10px] font-mono uppercase text-slate-500">Privacy Safeguards</span>
                  <div className="flex gap-2">
                    <button className="flex-1 py-2 text-xs font-bold border border-sky-500 bg-sky-500/10 text-sky-400 rounded-lg">PRIVATE</button>
                    <button className="flex-1 py-2 text-xs font-bold border border-slate-800 text-slate-400 hover:text-white rounded-lg">MESH-SHARED</button>
                  </div>
                </div>

                <div className="flex items-center justify-between text-sm">
                  <span className="text-slate-300">OCR Vision Fallback</span>
                  <div className="w-10 h-5 bg-sky-500 rounded-full relative"><div className="absolute right-1 top-1 size-3 bg-white rounded-full" /></div>
                </div>
              </div>

              <CyberButton className="w-full mt-4">Synthesize Metadata</CyberButton>
            </div>

            <div className="p-6 rounded-2xl border border-sky-500/20 bg-sky-500/5 flex flex-col gap-3 border-l-4 border-l-sky-500">
              <div className="flex items-center gap-2 text-sky-400">
                <Info className="size-5" />
                <span className="font-bold">System Telemetry</span>
              </div>
              <p className="text-xs text-slate-400 font-mono leading-relaxed">NEURAL PIPELINE CORES ONLINE (42% STACK). INFERENCE METRIC: 4.2 SECONDS LATENCY.</p>
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
};

const PlayerScreen = ({ onBack }) => (
  <div className="h-screen bg-slate-950 text-white flex flex-col">
    <header className="border-b border-slate-800 p-4 flex justify-between items-center bg-slate-900/30">
      <div className="flex items-center gap-6">
        <button onClick={onBack} className="p-2 hover:bg-white/5 rounded-xl"><ArrowLeft className="size-6 text-slate-400 hover:text-white transition-colors" /></button>
        <h1 className="text-xl font-bold flex items-center gap-3">
          <BookOpen className="text-sky-400 size-5" />
          Live Speech Transcription Space
        </h1>
      </div>
      <div className="flex items-center gap-4">
        <button className="p-2 hover:bg-white/5 rounded-xl text-slate-400"><Settings className="size-5" /></button>
        <button className="p-2 border border-sky-500/30 rounded-xl text-sky-400 bg-sky-500/10"><Accessibility className="size-5" /></button>
      </div>
    </header>

    <div className="flex-1 flex overflow-hidden p-6 gap-6">
      <div className="w-[450px] flex flex-col gap-4">
        <div className="flex-1 rounded-2xl border border-sky-500/30 bg-slate-900/10 shadow-[0_0_15px_rgba(14,165,233,0.1)] overflow-hidden flex flex-col">
          <div className="flex-1 bg-slate-900 relative">
            <img src="https://images.unsplash.com/photo-1614728263952-84ea206f99b6?w=600&auto=format&fit=crop" alt="ASL Signer" className="w-full h-full object-cover opacity-80" />
            <div className="absolute top-4 left-4 flex items-center gap-2 bg-slate-950/80 backdrop-blur px-3.5 py-1.5 rounded-full text-[10px] font-bold uppercase border border-slate-800">
              <div className="size-2 bg-red-500 rounded-full animate-pulse" /> ASL Interpreter Active
            </div>
          </div>
          <div className="h-16 bg-slate-900 flex items-center justify-between px-4 border-t border-slate-800">
            <div className="flex gap-2">
              <button className="size-10 flex items-center justify-center hover:bg-white/5 rounded-xl"><RotateCcw className="size-5 text-slate-400" /></button>
              <button className="size-10 flex items-center justify-center bg-sky-600 text-white rounded-xl"><PauseCircle className="size-5" /></button>
              <button className="size-10 flex items-center justify-center hover:bg-white/5 rounded-xl"><PlayCircle className="size-5 text-slate-400" /></button>
            </div>
            <button className="text-xs font-mono border border-slate-800 px-3 py-1.5 rounded-lg text-slate-400">1.0x Speed</button>
          </div>
        </div>
      </div>

      <div className="flex-1 flex flex-col rounded-2xl border border-slate-800 bg-slate-900/20 overflow-hidden">
        <div className="p-6 border-b border-slate-800 flex justify-between items-center bg-white/5">
          <h2 className="text-xl font-bold flex items-center gap-3"><div className="w-1.5 h-6 bg-sky-500 rounded" /> Linear Classical Vectors</h2>
          <span className="text-xs font-mono border border-slate-800 px-2 py-1 rounded text-slate-400">English (en)</span>
        </div>
        <div className="flex-1 overflow-y-auto p-8 space-y-8 leading-relaxed text-slate-300">
          <p className="text-lg">Welcome to the Live Speech Space. Today, we are reviewing classical mechanical systems and Newtonian vector spaces.</p>
          <p className="text-xl text-white relative">
            <div className="absolute -left-6 top-2.5 size-2 bg-sky-500 rounded-full animate-pulse" />
            In classical Newtonian mechanics, force is directly proportional to mass times acceleration: <span className="bg-sky-500/20 text-sky-400 font-bold px-1.5 py-0.5 rounded border border-sky-500/30">$\sum F = ma$</span>. However, when the mass vector changes, the change in momentum over time is expressed as <span className="text-sky-300 border-b border-dashed border-sky-500/50 pb-0.5 cursor-help">$F = \frac{dp}{dt} = m \frac{dv}{dt}$</span>.
          </p>
          <p className="text-lg">This differential form simplifies coordinate transformations across diverse inertial frames.</p>
        </div>
      </div>
    </div>
  </div>
);

const MediaIntegration = ({ onBack }) => {
  const [videoUrl, setVideoUrl] = useState('');
  const [videoNotes, setVideoNotes] = useState('');
  const [videoLoading, setVideoLoading] = useState(false);
  const [videoError, setVideoError] = useState('');

  const handleYoutubeSubmit = async (e) => {
    e.preventDefault();
    if (!videoUrl) return;
    setVideoLoading(true);
    setVideoError('');
    setVideoNotes('');
    try {
      const response = await fetch('http://127.0.0.1:8000/api/process-video', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ video_url: videoUrl }),
      });
      if (!response.ok) {
        throw new Error(`Failed with status: ${response.status}`);
      }
      const result = await response.json();
      if (result.status === 'success') {
        setVideoNotes(result.data.adapted_markdown);
      } else {
        throw new Error(result.message || 'Verification failed');
      }
    } catch (err) {
      console.error(err);
      setVideoError(err.message || 'An error occurred during video processing');
    } finally {
      setVideoLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0c0f24] text-white">
      <header className="h-[72px] border-b border-purple-500/10 flex items-center px-10 gap-6 bg-[#121635]/30 sticky top-0 z-50">
        <button onClick={onBack} className="p-2 text-purple-400 hover:bg-white/5 rounded-xl cursor-pointer"><ArrowLeft className="size-6" /></button>
        <h1 className="text-xl font-bold flex items-center gap-3">
          <PlayCircle className="text-purple-400" />
          YouTube Video Ingestion Lab
        </h1>
      </header>

      <main className="max-w-[800px] mx-auto py-16 px-4 flex flex-col gap-16">
        <div className="text-center flex flex-col gap-6">
          <h2 className="text-4xl font-extrabold tracking-tight text-white">YouTube Audio & Chapter Parser</h2>
          <p className="text-slate-300 text-lg leading-relaxed">Input a lecture video link. Our pipeline downloads the audio stream, segments chapters using AssemblyAI, and outputs structured academic summaries.</p>

          <form onSubmit={handleYoutubeSubmit} className="flex flex-col items-start gap-2 mt-4 relative w-full text-left">
            <label htmlFor="url-input" className="font-mono text-xs text-purple-400 uppercase ml-1">Video URL</label>
            <div className="relative w-full flex items-center">
              <Search className="absolute left-4 size-5 text-purple-300/60" />
              <input
                id="url-input"
                type="url"
                value={videoUrl}
                onChange={(e) => setVideoUrl(e.target.value)}
                placeholder="https://www.youtube.com/watch?v=..."
                className="w-full h-14 pl-12 pr-32 bg-[#121635] border border-purple-500/10 rounded-xl focus:ring-2 focus:ring-purple-400 focus:outline-none text-white text-sm"
              />
              <button
                type="submit"
                onClick={handleYoutubeSubmit}
                disabled={videoLoading}
                className="absolute right-2 h-10 px-5 bg-purple-600 text-white font-bold rounded-lg flex items-center gap-2 hover:bg-purple-500 transition-all text-xs uppercase bouncy-pill disabled:opacity-50"
              >
                {videoLoading ? 'Parsing...' : 'Parse'} <Zap className="size-4" />
              </button>
            </div>
          </form>

          {videoLoading && (
            <div className="flex flex-col items-center justify-center p-12 border border-purple-500/10 rounded-2xl bg-[#121635]/20 mt-6 levitate">
              <div className="size-12 border-4 border-purple-500/20 border-t-purple-500 rounded-full animate-spin mb-4" />
              <p className="text-purple-300 font-bold text-sm">Parsing lecture video audio and neural mapping... 🚀</p>
            </div>
          )}

          {videoError && (
            <div className="p-4 border border-rose-500/20 rounded-xl bg-rose-500/10 text-rose-400 text-sm mt-6">
              ⚠️ {videoError}
            </div>
          )}

          {videoNotes && (
            <GlassCard className="p-8 flex flex-col gap-6 mt-6 border-purple-500/30 bg-[#121635]/30 text-left">
              <div className="flex items-center gap-3 border-b border-purple-500/10 pb-4">
                <Zap className="text-purple-400 size-7" />
                <h3 className="text-xl font-bold text-white">Adapted Lecture Summaries 📖✨</h3>
              </div>
              <div className="text-gray-300 mt-4 prose prose-invert max-w-none">
                <ReactMarkdown>{videoNotes}</ReactMarkdown>
              </div>
            </GlassCard>
          )}
        </div>

        <div className="flex flex-col gap-8">
          <GlassCard className="p-8 flex flex-col gap-6">
            <div className="flex items-center gap-3 border-b border-slate-800 pb-4">
              <Radar className="text-sky-400 size-7" />
              <h3 className="text-xl font-bold">Extracted STEM Topics</h3>
            </div>
            <div className="flex flex-wrap gap-4">
              {['Classical Mechanics', 'Newtonian Vectors', 'Differential Momentum', 'Inertial Coordinate Frames', 'Academic Ingestion'].map((topic, i) => (
                <div key={topic} className={cn("px-4 py-2 border-l-4 font-mono text-sm bg-slate-900 border-slate-800 rounded-r-lg", i < 2 ? "border-sky-500 text-white font-bold" : i === 2 ? "border-indigo-500 text-indigo-400" : "border-slate-700 text-slate-400")}>
                  {topic}
                </div>
              ))}
            </div>
          </GlassCard>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/20 p-8 flex flex-col gap-6">
            <div className="flex items-center gap-3 border-b border-slate-800 pb-4">
              <LayoutDashboard className="text-sky-400 size-7" />
              <h3 className="text-xl font-bold">Chapter Timeline</h3>
            </div>
            <div className="flex flex-col gap-8 border-l-2 border-slate-850 ml-4 pl-6 relative">
              {[
                { time: '00:00', title: 'Vector Momentum Introduction', desc: 'Analyzing force sums and basic equations in simple setups.' },
                { time: '12:45', title: 'Differential Derivatives', desc: 'Understanding momentum derivatives over time using LaTeX.' },
                { time: '28:30', title: 'Inertial Transformation Structures', desc: 'Applying vector models to coordinate spaces in physical simulations.' }
              ].map((chapter, i) => (
                <div key={i} className="relative">
                  <div className={cn("absolute -left-[31px] top-1 size-3 rounded-full", i === 0 ? "bg-sky-500 shadow-[0_0_8px_rgba(14,165,233,0.8)]" : "bg-slate-700")} />
                  <div className="flex items-center gap-4">
                    <span className={cn("font-mono text-sm min-w-[60px]", i === 0 ? "text-sky-400" : "text-slate-500")}>{chapter.time}</span>
                    <div>
                      <h4 className="font-bold">{chapter.title}</h4>
                      <p className="text-sm text-slate-400 mt-1">{chapter.desc}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </section>

          <section className="rounded-2xl border border-slate-800 bg-slate-900/20 p-8 flex flex-col gap-6">
            <div className="flex items-center gap-3 border-b border-slate-800 pb-4">
              <PlayCircle className="text-sky-400 size-7" />
              <h3 className="text-xl font-bold">Interactive Frame Capture</h3>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {[1, 2, 3].map(i => (
                <div key={i} className="flex flex-col gap-3 group">
                  <div className="aspect-video relative overflow-hidden bg-slate-900 border border-slate-800 rounded-xl">
                    <img src={`https://picsum.photos/seed/${i + 50}/400/225`} className="w-full h-full object-cover opacity-80 group-hover:opacity-100 transition-opacity duration-300" />
                    <div className="absolute bottom-2 right-2 bg-slate-950/80 backdrop-blur px-2 py-0.5 rounded text-[10px] font-mono text-sky-400">0{i}:12</div>
                  </div>
                  <p className="text-xs text-slate-400 leading-relaxed">Visual keyframe {i} parsed. Neural topic match: Classical Momentum.</p>
                </div>
              ))}
            </div>
          </section>
        </div>
      </main>
    </div>
  );
};

const NotesScreen = ({ onBack }) => (
  <div className="min-h-screen bg-slate-950 text-white">
    <header className="h-[72px] border-b border-slate-800 flex items-center px-10 gap-6 bg-slate-900/30 sticky top-0 z-50">
      <button onClick={onBack} className="p-2 text-sky-400 hover:bg-white/5 rounded-xl cursor-pointer"><ArrowLeft className="size-6" /></button>
      <h1 className="text-xl font-bold">Academic Synapse Notes</h1>
    </header>

    <main className="max-w-[1000px] mx-auto py-16 px-4 flex flex-col gap-10">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-bold flex items-center gap-3"><div className="w-1.5 h-8 bg-sky-500 rounded" /> Active Transcripts</h2>
        <CyberButton icon={Zap}>Synthesize New</CyberButton>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {[
          { title: 'Newtonian Forces & Inertia', date: 'Synthesized 2h ago', category: 'Physics', content: 'Evaluation of force equations inside dynamic coordinate systems...' },
          { title: 'Causal Cosegmentation', date: 'Synthesized 1d ago', category: 'Linguistics', content: 'Applying translation safeguards to preserve scientific statements...' },
          { title: 'LaTeX Formula Rendering', date: 'Synthesized 3d ago', category: 'Math', content: 'Formatting complex fractions using proper mathematical markup...' },
          { title: 'Cognitive Accommodations', date: 'Synthesized 1w ago', category: 'Accessibility', content: 'Toggling open-dyslexic spacing layouts to enhance reading flow...' }
        ].map((note, i) => (
          <GlassCard key={i} className="p-6 group cursor-pointer border-l-4 border-l-transparent hover:border-l-sky-500">
            <div className="flex justify-between items-start mb-4">
              <span className="text-[10px] font-mono text-sky-400 uppercase tracking-widest bg-sky-500/10 px-2 py-0.5 rounded border border-sky-500/20">{note.category}</span>
              <span className="text-[10px] font-mono text-slate-500">{note.date}</span>
            </div>
            <h3 className="text-xl font-bold mb-2 group-hover:text-sky-400 transition-colors">{note.title}</h3>
            <p className="text-sm text-slate-400 line-clamp-3 leading-relaxed">{note.content}</p>
            <div className="mt-6 flex justify-between items-center text-xs font-bold">
              <span className="text-slate-500">EST. 4 MIN READ</span>
              <div className="flex items-center gap-2">
                <div className="size-2 bg-sky-500 rounded-full" />
                <span className="text-sky-400 font-mono text-[10px]">SYNCED</span>
              </div>
            </div>
          </GlassCard>
        ))}
      </div>
    </main>
  </div>
);

const SettingsScreen = ({ onBack, profile, togglePreference }) => (
  <div className="min-h-screen bg-slate-950 text-white">
    <header className="h-[72px] border-b border-slate-800 flex items-center px-10 gap-6 bg-slate-900/30 sticky top-0 z-50">
      <button onClick={onBack} className="p-2 text-sky-400 hover:bg-white/5 rounded-xl cursor-pointer"><ArrowLeft className="size-6" /></button>
      <h1 className="text-xl font-bold">System Configurations</h1>
    </header>

    <main className="max-w-[800px] mx-auto py-16 px-4 flex flex-col gap-12">
      <div className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold border-b border-slate-800 pb-4">Theme & Typography</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <GlassCard active={profile.high_contrast} onClick={() => togglePreference('high_contrast', profile.high_contrast)} className="p-6 flex flex-col gap-4 cursor-pointer">
            <div className="flex justify-between items-center">
              <h3 className="font-bold">High Contrast Boost</h3>
              {profile.high_contrast && <CheckCircle2 className="text-sky-400 size-5" />}
            </div>
            <p className="text-sm text-slate-400">Forces deep-contrast obsidian overrides to target low vision fatigue.</p>
          </GlassCard>

          <GlassCard active={profile.dyslexia_friendly} onClick={() => togglePreference('dyslexia_friendly', profile.dyslexia_friendly)} className="p-6 flex flex-col gap-4 cursor-pointer">
            <div className="flex justify-between items-center">
              <h3 className="font-bold">Dyslexia-Friendly Layout</h3>
              {profile.dyslexia_friendly && <CheckCircle2 className="text-sky-400 size-5" />}
            </div>
            <p className="text-sm text-slate-400">Optimizes letter-spacing thresholds to simplify parsing long structures.</p>
          </GlassCard>
        </div>
      </div>

      <div className="flex flex-col gap-8">
        <h2 className="text-3xl font-bold border-b border-slate-800 pb-4">Ingestion & Translation Toggles</h2>
        <div className="flex flex-col gap-4">
          {[
            { key: 'dyslexia_friendly', label: 'Dyslexia-Friendly Spacing', desc: 'Persist Open-Dyslexic spacing variables across learning documents.' },
            { key: 'high_contrast', label: 'Maximum High Contrast Override', desc: 'Forces pure slate ratios for photophobia mitigation.' },
            { key: 'sign_language_preference', label: 'Sign Language Avatar Synced', desc: 'Auto-embeds American Sign Language (ASL) videos beside active streams.' }
          ].map((s) => (
            <div
              key={s.key}
              onClick={() => togglePreference(s.key, profile[s.key])}
              className="flex items-center justify-between p-6 rounded-2xl border border-slate-800 bg-slate-900/10 cursor-pointer hover:border-slate-700 transition-colors"
            >
              <div>
                <h4 className="font-bold text-white">{s.label}</h4>
                <p className="text-sm text-slate-400 mt-1">{s.desc}</p>
              </div>
              <div className={cn("w-12 h-6 rounded-full relative transition-colors", profile[s.key] ? "bg-sky-500" : "bg-slate-800")}>
                <div className={cn("absolute top-1 size-4 bg-white rounded-full transition-all", profile[s.key] ? "right-1" : "left-1")} />
              </div>
            </div>
          ))}
        </div>
      </div>

      <div className="flex justify-end pt-8 border-t border-slate-800">
        <CyberButton variant="outline" onClick={onBack} className="mr-4">Confirm Settings</CyberButton>
      </div>
    </main>
  </div>
);

export default function App() {
  const [screen, setScreen] = useState('login');
  const { profile, setProfile } = useAccessibility();

  // Optimistic UI state-syncing handler that persists directly to Supabase profiles
  const togglePreference = async (key, currentValue) => {
    const newValue = !currentValue;

    // 1. Optimistic Local State Sync
    setProfile(prev => ({
      ...prev,
      [key]: newValue
    }));

    // 2. Suppress database synchronization if active session doesn't exist
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (user) {
        const { error } = await supabase
          .from('profiles')
          .update({
            [key]: newValue,
            updated_at: new Date().toISOString()
          })
          .eq('id', user.id);

        if (error) throw error;
        console.log(`[Supabase Persistence] Synchronized '${key}' preference state value:`, newValue);
      }
    } catch (err) {
      console.error(`[Supabase ERR] Fails to update preference state for '${key}':`, err);
    }
  };

  // Monitor Auth state changes to route users optimally
  useEffect(() => {
    async function checkActiveSession() {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        setScreen('dashboard');
      }
    }
    checkActiveSession();
  }, []);

  return (
    <div className="min-h-screen">
      <AnimatePresence mode="wait">
        <motion.div
          key={screen}
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -10 }}
          transition={{ duration: 0.35, ease: "easeOut" }}
        >
          {screen === 'login' && <LoginScreen onNext={() => setScreen('reg0')} />}
          {screen === 'reg0' && <Registration0 onNext={() => setScreen('reg1')} />}
          {screen === 'reg1' && <Registration1 onNext={() => setScreen('reg2')} />}
          {screen === 'reg2' && <Registration2 onNext={() => setScreen('reg3')} profile={profile} togglePreference={togglePreference} />}
          {screen === 'reg3' && <Registration3 onNext={() => setScreen('dashboard')} onPrev={() => setScreen('reg2')} profile={profile} togglePreference={togglePreference} />}
          {screen === 'dashboard' && <Dashboard onNavigate={(s) => setScreen(s)} profile={profile} />}
          {screen === 'hive' && <HiveScreen onBack={() => setScreen('dashboard')} />}
          {screen === 'uploads' && <UploadCockpit onBack={() => setScreen('dashboard')} />}
          {screen === 'player' && <PlayerScreen onBack={() => setScreen('dashboard')} />}
          {screen === 'media' && <MediaIntegration onBack={() => setScreen('dashboard')} />}
          {screen === 'notes' && <NotesScreen onBack={() => setScreen('dashboard')} />}
          {screen === 'settings' && <SettingsScreen onBack={() => setScreen('dashboard')} profile={profile} togglePreference={togglePreference} />}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
